package com.wetech.ryutsumodel.model.entity;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class TmhanyoExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table tmhanyo
	 * @mbg.generated  Sun Sep 18 16:27:33 CST 2022
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table tmhanyo
	 * @mbg.generated  Sun Sep 18 16:27:33 CST 2022
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table tmhanyo
	 * @mbg.generated  Sun Sep 18 16:27:33 CST 2022
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tmhanyo
	 * @mbg.generated  Sun Sep 18 16:27:33 CST 2022
	 */
	public TmhanyoExample() {
		oredCriteria = new ArrayList<>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tmhanyo
	 * @mbg.generated  Sun Sep 18 16:27:33 CST 2022
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tmhanyo
	 * @mbg.generated  Sun Sep 18 16:27:33 CST 2022
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tmhanyo
	 * @mbg.generated  Sun Sep 18 16:27:33 CST 2022
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tmhanyo
	 * @mbg.generated  Sun Sep 18 16:27:33 CST 2022
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tmhanyo
	 * @mbg.generated  Sun Sep 18 16:27:33 CST 2022
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tmhanyo
	 * @mbg.generated  Sun Sep 18 16:27:33 CST 2022
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tmhanyo
	 * @mbg.generated  Sun Sep 18 16:27:33 CST 2022
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tmhanyo
	 * @mbg.generated  Sun Sep 18 16:27:33 CST 2022
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tmhanyo
	 * @mbg.generated  Sun Sep 18 16:27:33 CST 2022
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tmhanyo
	 * @mbg.generated  Sun Sep 18 16:27:33 CST 2022
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table tmhanyo
	 * @mbg.generated  Sun Sep 18 16:27:33 CST 2022
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		protected void addCriterionForJDBCDate(String condition, Date value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			addCriterion(condition, new java.sql.Date(value.getTime()), property);
		}

		protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
			if (values == null || values.size() == 0) {
				throw new RuntimeException("Value list for " + property + " cannot be null or empty");
			}
			List<java.sql.Date> dateList = new ArrayList<>();
			Iterator<Date> iter = values.iterator();
			while (iter.hasNext()) {
				dateList.add(new java.sql.Date(iter.next().getTime()));
			}
			addCriterion(condition, dateList, property);
		}

		protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
		}

		public Criteria andBunrui_codIsNull() {
			addCriterion("bunrui_cod is null");
			return (Criteria) this;
		}

		public Criteria andBunrui_codIsNotNull() {
			addCriterion("bunrui_cod is not null");
			return (Criteria) this;
		}

		public Criteria andBunrui_codEqualTo(String value) {
			addCriterion("bunrui_cod =", value, "bunrui_cod");
			return (Criteria) this;
		}

		public Criteria andBunrui_codNotEqualTo(String value) {
			addCriterion("bunrui_cod <>", value, "bunrui_cod");
			return (Criteria) this;
		}

		public Criteria andBunrui_codGreaterThan(String value) {
			addCriterion("bunrui_cod >", value, "bunrui_cod");
			return (Criteria) this;
		}

		public Criteria andBunrui_codGreaterThanOrEqualTo(String value) {
			addCriterion("bunrui_cod >=", value, "bunrui_cod");
			return (Criteria) this;
		}

		public Criteria andBunrui_codLessThan(String value) {
			addCriterion("bunrui_cod <", value, "bunrui_cod");
			return (Criteria) this;
		}

		public Criteria andBunrui_codLessThanOrEqualTo(String value) {
			addCriterion("bunrui_cod <=", value, "bunrui_cod");
			return (Criteria) this;
		}

		public Criteria andBunrui_codLike(String value) {
			addCriterion("bunrui_cod like", value, "bunrui_cod");
			return (Criteria) this;
		}

		public Criteria andBunrui_codNotLike(String value) {
			addCriterion("bunrui_cod not like", value, "bunrui_cod");
			return (Criteria) this;
		}

		public Criteria andBunrui_codIn(List<String> values) {
			addCriterion("bunrui_cod in", values, "bunrui_cod");
			return (Criteria) this;
		}

		public Criteria andBunrui_codNotIn(List<String> values) {
			addCriterion("bunrui_cod not in", values, "bunrui_cod");
			return (Criteria) this;
		}

		public Criteria andBunrui_codBetween(String value1, String value2) {
			addCriterion("bunrui_cod between", value1, value2, "bunrui_cod");
			return (Criteria) this;
		}

		public Criteria andBunrui_codNotBetween(String value1, String value2) {
			addCriterion("bunrui_cod not between", value1, value2, "bunrui_cod");
			return (Criteria) this;
		}

		public Criteria andKbn1IsNull() {
			addCriterion("kbn1 is null");
			return (Criteria) this;
		}

		public Criteria andKbn1IsNotNull() {
			addCriterion("kbn1 is not null");
			return (Criteria) this;
		}

		public Criteria andKbn1EqualTo(String value) {
			addCriterion("kbn1 =", value, "kbn1");
			return (Criteria) this;
		}

		public Criteria andKbn1NotEqualTo(String value) {
			addCriterion("kbn1 <>", value, "kbn1");
			return (Criteria) this;
		}

		public Criteria andKbn1GreaterThan(String value) {
			addCriterion("kbn1 >", value, "kbn1");
			return (Criteria) this;
		}

		public Criteria andKbn1GreaterThanOrEqualTo(String value) {
			addCriterion("kbn1 >=", value, "kbn1");
			return (Criteria) this;
		}

		public Criteria andKbn1LessThan(String value) {
			addCriterion("kbn1 <", value, "kbn1");
			return (Criteria) this;
		}

		public Criteria andKbn1LessThanOrEqualTo(String value) {
			addCriterion("kbn1 <=", value, "kbn1");
			return (Criteria) this;
		}

		public Criteria andKbn1Like(String value) {
			addCriterion("kbn1 like", value, "kbn1");
			return (Criteria) this;
		}

		public Criteria andKbn1NotLike(String value) {
			addCriterion("kbn1 not like", value, "kbn1");
			return (Criteria) this;
		}

		public Criteria andKbn1In(List<String> values) {
			addCriterion("kbn1 in", values, "kbn1");
			return (Criteria) this;
		}

		public Criteria andKbn1NotIn(List<String> values) {
			addCriterion("kbn1 not in", values, "kbn1");
			return (Criteria) this;
		}

		public Criteria andKbn1Between(String value1, String value2) {
			addCriterion("kbn1 between", value1, value2, "kbn1");
			return (Criteria) this;
		}

		public Criteria andKbn1NotBetween(String value1, String value2) {
			addCriterion("kbn1 not between", value1, value2, "kbn1");
			return (Criteria) this;
		}

		public Criteria andKbn2IsNull() {
			addCriterion("kbn2 is null");
			return (Criteria) this;
		}

		public Criteria andKbn2IsNotNull() {
			addCriterion("kbn2 is not null");
			return (Criteria) this;
		}

		public Criteria andKbn2EqualTo(String value) {
			addCriterion("kbn2 =", value, "kbn2");
			return (Criteria) this;
		}

		public Criteria andKbn2NotEqualTo(String value) {
			addCriterion("kbn2 <>", value, "kbn2");
			return (Criteria) this;
		}

		public Criteria andKbn2GreaterThan(String value) {
			addCriterion("kbn2 >", value, "kbn2");
			return (Criteria) this;
		}

		public Criteria andKbn2GreaterThanOrEqualTo(String value) {
			addCriterion("kbn2 >=", value, "kbn2");
			return (Criteria) this;
		}

		public Criteria andKbn2LessThan(String value) {
			addCriterion("kbn2 <", value, "kbn2");
			return (Criteria) this;
		}

		public Criteria andKbn2LessThanOrEqualTo(String value) {
			addCriterion("kbn2 <=", value, "kbn2");
			return (Criteria) this;
		}

		public Criteria andKbn2Like(String value) {
			addCriterion("kbn2 like", value, "kbn2");
			return (Criteria) this;
		}

		public Criteria andKbn2NotLike(String value) {
			addCriterion("kbn2 not like", value, "kbn2");
			return (Criteria) this;
		}

		public Criteria andKbn2In(List<String> values) {
			addCriterion("kbn2 in", values, "kbn2");
			return (Criteria) this;
		}

		public Criteria andKbn2NotIn(List<String> values) {
			addCriterion("kbn2 not in", values, "kbn2");
			return (Criteria) this;
		}

		public Criteria andKbn2Between(String value1, String value2) {
			addCriterion("kbn2 between", value1, value2, "kbn2");
			return (Criteria) this;
		}

		public Criteria andKbn2NotBetween(String value1, String value2) {
			addCriterion("kbn2 not between", value1, value2, "kbn2");
			return (Criteria) this;
		}

		public Criteria andTekiyostr_ymdIsNull() {
			addCriterion("tekiyostr_ymd is null");
			return (Criteria) this;
		}

		public Criteria andTekiyostr_ymdIsNotNull() {
			addCriterion("tekiyostr_ymd is not null");
			return (Criteria) this;
		}

		public Criteria andTekiyostr_ymdEqualTo(Date value) {
			addCriterionForJDBCDate("tekiyostr_ymd =", value, "tekiyostr_ymd");
			return (Criteria) this;
		}

		public Criteria andTekiyostr_ymdNotEqualTo(Date value) {
			addCriterionForJDBCDate("tekiyostr_ymd <>", value, "tekiyostr_ymd");
			return (Criteria) this;
		}

		public Criteria andTekiyostr_ymdGreaterThan(Date value) {
			addCriterionForJDBCDate("tekiyostr_ymd >", value, "tekiyostr_ymd");
			return (Criteria) this;
		}

		public Criteria andTekiyostr_ymdGreaterThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("tekiyostr_ymd >=", value, "tekiyostr_ymd");
			return (Criteria) this;
		}

		public Criteria andTekiyostr_ymdLessThan(Date value) {
			addCriterionForJDBCDate("tekiyostr_ymd <", value, "tekiyostr_ymd");
			return (Criteria) this;
		}

		public Criteria andTekiyostr_ymdLessThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("tekiyostr_ymd <=", value, "tekiyostr_ymd");
			return (Criteria) this;
		}

		public Criteria andTekiyostr_ymdIn(List<Date> values) {
			addCriterionForJDBCDate("tekiyostr_ymd in", values, "tekiyostr_ymd");
			return (Criteria) this;
		}

		public Criteria andTekiyostr_ymdNotIn(List<Date> values) {
			addCriterionForJDBCDate("tekiyostr_ymd not in", values, "tekiyostr_ymd");
			return (Criteria) this;
		}

		public Criteria andTekiyostr_ymdBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("tekiyostr_ymd between", value1, value2, "tekiyostr_ymd");
			return (Criteria) this;
		}

		public Criteria andTekiyostr_ymdNotBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("tekiyostr_ymd not between", value1, value2, "tekiyostr_ymd");
			return (Criteria) this;
		}

		public Criteria andKbn_knj1IsNull() {
			addCriterion("kbn_knj1 is null");
			return (Criteria) this;
		}

		public Criteria andKbn_knj1IsNotNull() {
			addCriterion("kbn_knj1 is not null");
			return (Criteria) this;
		}

		public Criteria andKbn_knj1EqualTo(String value) {
			addCriterion("kbn_knj1 =", value, "kbn_knj1");
			return (Criteria) this;
		}

		public Criteria andKbn_knj1NotEqualTo(String value) {
			addCriterion("kbn_knj1 <>", value, "kbn_knj1");
			return (Criteria) this;
		}

		public Criteria andKbn_knj1GreaterThan(String value) {
			addCriterion("kbn_knj1 >", value, "kbn_knj1");
			return (Criteria) this;
		}

		public Criteria andKbn_knj1GreaterThanOrEqualTo(String value) {
			addCriterion("kbn_knj1 >=", value, "kbn_knj1");
			return (Criteria) this;
		}

		public Criteria andKbn_knj1LessThan(String value) {
			addCriterion("kbn_knj1 <", value, "kbn_knj1");
			return (Criteria) this;
		}

		public Criteria andKbn_knj1LessThanOrEqualTo(String value) {
			addCriterion("kbn_knj1 <=", value, "kbn_knj1");
			return (Criteria) this;
		}

		public Criteria andKbn_knj1Like(String value) {
			addCriterion("kbn_knj1 like", value, "kbn_knj1");
			return (Criteria) this;
		}

		public Criteria andKbn_knj1NotLike(String value) {
			addCriterion("kbn_knj1 not like", value, "kbn_knj1");
			return (Criteria) this;
		}

		public Criteria andKbn_knj1In(List<String> values) {
			addCriterion("kbn_knj1 in", values, "kbn_knj1");
			return (Criteria) this;
		}

		public Criteria andKbn_knj1NotIn(List<String> values) {
			addCriterion("kbn_knj1 not in", values, "kbn_knj1");
			return (Criteria) this;
		}

		public Criteria andKbn_knj1Between(String value1, String value2) {
			addCriterion("kbn_knj1 between", value1, value2, "kbn_knj1");
			return (Criteria) this;
		}

		public Criteria andKbn_knj1NotBetween(String value1, String value2) {
			addCriterion("kbn_knj1 not between", value1, value2, "kbn_knj1");
			return (Criteria) this;
		}

		public Criteria andKbn_knj2IsNull() {
			addCriterion("kbn_knj2 is null");
			return (Criteria) this;
		}

		public Criteria andKbn_knj2IsNotNull() {
			addCriterion("kbn_knj2 is not null");
			return (Criteria) this;
		}

		public Criteria andKbn_knj2EqualTo(String value) {
			addCriterion("kbn_knj2 =", value, "kbn_knj2");
			return (Criteria) this;
		}

		public Criteria andKbn_knj2NotEqualTo(String value) {
			addCriterion("kbn_knj2 <>", value, "kbn_knj2");
			return (Criteria) this;
		}

		public Criteria andKbn_knj2GreaterThan(String value) {
			addCriterion("kbn_knj2 >", value, "kbn_knj2");
			return (Criteria) this;
		}

		public Criteria andKbn_knj2GreaterThanOrEqualTo(String value) {
			addCriterion("kbn_knj2 >=", value, "kbn_knj2");
			return (Criteria) this;
		}

		public Criteria andKbn_knj2LessThan(String value) {
			addCriterion("kbn_knj2 <", value, "kbn_knj2");
			return (Criteria) this;
		}

		public Criteria andKbn_knj2LessThanOrEqualTo(String value) {
			addCriterion("kbn_knj2 <=", value, "kbn_knj2");
			return (Criteria) this;
		}

		public Criteria andKbn_knj2Like(String value) {
			addCriterion("kbn_knj2 like", value, "kbn_knj2");
			return (Criteria) this;
		}

		public Criteria andKbn_knj2NotLike(String value) {
			addCriterion("kbn_knj2 not like", value, "kbn_knj2");
			return (Criteria) this;
		}

		public Criteria andKbn_knj2In(List<String> values) {
			addCriterion("kbn_knj2 in", values, "kbn_knj2");
			return (Criteria) this;
		}

		public Criteria andKbn_knj2NotIn(List<String> values) {
			addCriterion("kbn_knj2 not in", values, "kbn_knj2");
			return (Criteria) this;
		}

		public Criteria andKbn_knj2Between(String value1, String value2) {
			addCriterion("kbn_knj2 between", value1, value2, "kbn_knj2");
			return (Criteria) this;
		}

		public Criteria andKbn_knj2NotBetween(String value1, String value2) {
			addCriterion("kbn_knj2 not between", value1, value2, "kbn_knj2");
			return (Criteria) this;
		}

		public Criteria andStr1IsNull() {
			addCriterion("str1 is null");
			return (Criteria) this;
		}

		public Criteria andStr1IsNotNull() {
			addCriterion("str1 is not null");
			return (Criteria) this;
		}

		public Criteria andStr1EqualTo(String value) {
			addCriterion("str1 =", value, "str1");
			return (Criteria) this;
		}

		public Criteria andStr1NotEqualTo(String value) {
			addCriterion("str1 <>", value, "str1");
			return (Criteria) this;
		}

		public Criteria andStr1GreaterThan(String value) {
			addCriterion("str1 >", value, "str1");
			return (Criteria) this;
		}

		public Criteria andStr1GreaterThanOrEqualTo(String value) {
			addCriterion("str1 >=", value, "str1");
			return (Criteria) this;
		}

		public Criteria andStr1LessThan(String value) {
			addCriterion("str1 <", value, "str1");
			return (Criteria) this;
		}

		public Criteria andStr1LessThanOrEqualTo(String value) {
			addCriterion("str1 <=", value, "str1");
			return (Criteria) this;
		}

		public Criteria andStr1Like(String value) {
			addCriterion("str1 like", value, "str1");
			return (Criteria) this;
		}

		public Criteria andStr1NotLike(String value) {
			addCriterion("str1 not like", value, "str1");
			return (Criteria) this;
		}

		public Criteria andStr1In(List<String> values) {
			addCriterion("str1 in", values, "str1");
			return (Criteria) this;
		}

		public Criteria andStr1NotIn(List<String> values) {
			addCriterion("str1 not in", values, "str1");
			return (Criteria) this;
		}

		public Criteria andStr1Between(String value1, String value2) {
			addCriterion("str1 between", value1, value2, "str1");
			return (Criteria) this;
		}

		public Criteria andStr1NotBetween(String value1, String value2) {
			addCriterion("str1 not between", value1, value2, "str1");
			return (Criteria) this;
		}

		public Criteria andStr2IsNull() {
			addCriterion("str2 is null");
			return (Criteria) this;
		}

		public Criteria andStr2IsNotNull() {
			addCriterion("str2 is not null");
			return (Criteria) this;
		}

		public Criteria andStr2EqualTo(String value) {
			addCriterion("str2 =", value, "str2");
			return (Criteria) this;
		}

		public Criteria andStr2NotEqualTo(String value) {
			addCriterion("str2 <>", value, "str2");
			return (Criteria) this;
		}

		public Criteria andStr2GreaterThan(String value) {
			addCriterion("str2 >", value, "str2");
			return (Criteria) this;
		}

		public Criteria andStr2GreaterThanOrEqualTo(String value) {
			addCriterion("str2 >=", value, "str2");
			return (Criteria) this;
		}

		public Criteria andStr2LessThan(String value) {
			addCriterion("str2 <", value, "str2");
			return (Criteria) this;
		}

		public Criteria andStr2LessThanOrEqualTo(String value) {
			addCriterion("str2 <=", value, "str2");
			return (Criteria) this;
		}

		public Criteria andStr2Like(String value) {
			addCriterion("str2 like", value, "str2");
			return (Criteria) this;
		}

		public Criteria andStr2NotLike(String value) {
			addCriterion("str2 not like", value, "str2");
			return (Criteria) this;
		}

		public Criteria andStr2In(List<String> values) {
			addCriterion("str2 in", values, "str2");
			return (Criteria) this;
		}

		public Criteria andStr2NotIn(List<String> values) {
			addCriterion("str2 not in", values, "str2");
			return (Criteria) this;
		}

		public Criteria andStr2Between(String value1, String value2) {
			addCriterion("str2 between", value1, value2, "str2");
			return (Criteria) this;
		}

		public Criteria andStr2NotBetween(String value1, String value2) {
			addCriterion("str2 not between", value1, value2, "str2");
			return (Criteria) this;
		}

		public Criteria andStr3IsNull() {
			addCriterion("str3 is null");
			return (Criteria) this;
		}

		public Criteria andStr3IsNotNull() {
			addCriterion("str3 is not null");
			return (Criteria) this;
		}

		public Criteria andStr3EqualTo(String value) {
			addCriterion("str3 =", value, "str3");
			return (Criteria) this;
		}

		public Criteria andStr3NotEqualTo(String value) {
			addCriterion("str3 <>", value, "str3");
			return (Criteria) this;
		}

		public Criteria andStr3GreaterThan(String value) {
			addCriterion("str3 >", value, "str3");
			return (Criteria) this;
		}

		public Criteria andStr3GreaterThanOrEqualTo(String value) {
			addCriterion("str3 >=", value, "str3");
			return (Criteria) this;
		}

		public Criteria andStr3LessThan(String value) {
			addCriterion("str3 <", value, "str3");
			return (Criteria) this;
		}

		public Criteria andStr3LessThanOrEqualTo(String value) {
			addCriterion("str3 <=", value, "str3");
			return (Criteria) this;
		}

		public Criteria andStr3Like(String value) {
			addCriterion("str3 like", value, "str3");
			return (Criteria) this;
		}

		public Criteria andStr3NotLike(String value) {
			addCriterion("str3 not like", value, "str3");
			return (Criteria) this;
		}

		public Criteria andStr3In(List<String> values) {
			addCriterion("str3 in", values, "str3");
			return (Criteria) this;
		}

		public Criteria andStr3NotIn(List<String> values) {
			addCriterion("str3 not in", values, "str3");
			return (Criteria) this;
		}

		public Criteria andStr3Between(String value1, String value2) {
			addCriterion("str3 between", value1, value2, "str3");
			return (Criteria) this;
		}

		public Criteria andStr3NotBetween(String value1, String value2) {
			addCriterion("str3 not between", value1, value2, "str3");
			return (Criteria) this;
		}

		public Criteria andNum1IsNull() {
			addCriterion("num1 is null");
			return (Criteria) this;
		}

		public Criteria andNum1IsNotNull() {
			addCriterion("num1 is not null");
			return (Criteria) this;
		}

		public Criteria andNum1EqualTo(Integer value) {
			addCriterion("num1 =", value, "num1");
			return (Criteria) this;
		}

		public Criteria andNum1NotEqualTo(Integer value) {
			addCriterion("num1 <>", value, "num1");
			return (Criteria) this;
		}

		public Criteria andNum1GreaterThan(Integer value) {
			addCriterion("num1 >", value, "num1");
			return (Criteria) this;
		}

		public Criteria andNum1GreaterThanOrEqualTo(Integer value) {
			addCriterion("num1 >=", value, "num1");
			return (Criteria) this;
		}

		public Criteria andNum1LessThan(Integer value) {
			addCriterion("num1 <", value, "num1");
			return (Criteria) this;
		}

		public Criteria andNum1LessThanOrEqualTo(Integer value) {
			addCriterion("num1 <=", value, "num1");
			return (Criteria) this;
		}

		public Criteria andNum1In(List<Integer> values) {
			addCriterion("num1 in", values, "num1");
			return (Criteria) this;
		}

		public Criteria andNum1NotIn(List<Integer> values) {
			addCriterion("num1 not in", values, "num1");
			return (Criteria) this;
		}

		public Criteria andNum1Between(Integer value1, Integer value2) {
			addCriterion("num1 between", value1, value2, "num1");
			return (Criteria) this;
		}

		public Criteria andNum1NotBetween(Integer value1, Integer value2) {
			addCriterion("num1 not between", value1, value2, "num1");
			return (Criteria) this;
		}

		public Criteria andNum2IsNull() {
			addCriterion("num2 is null");
			return (Criteria) this;
		}

		public Criteria andNum2IsNotNull() {
			addCriterion("num2 is not null");
			return (Criteria) this;
		}

		public Criteria andNum2EqualTo(Integer value) {
			addCriterion("num2 =", value, "num2");
			return (Criteria) this;
		}

		public Criteria andNum2NotEqualTo(Integer value) {
			addCriterion("num2 <>", value, "num2");
			return (Criteria) this;
		}

		public Criteria andNum2GreaterThan(Integer value) {
			addCriterion("num2 >", value, "num2");
			return (Criteria) this;
		}

		public Criteria andNum2GreaterThanOrEqualTo(Integer value) {
			addCriterion("num2 >=", value, "num2");
			return (Criteria) this;
		}

		public Criteria andNum2LessThan(Integer value) {
			addCriterion("num2 <", value, "num2");
			return (Criteria) this;
		}

		public Criteria andNum2LessThanOrEqualTo(Integer value) {
			addCriterion("num2 <=", value, "num2");
			return (Criteria) this;
		}

		public Criteria andNum2In(List<Integer> values) {
			addCriterion("num2 in", values, "num2");
			return (Criteria) this;
		}

		public Criteria andNum2NotIn(List<Integer> values) {
			addCriterion("num2 not in", values, "num2");
			return (Criteria) this;
		}

		public Criteria andNum2Between(Integer value1, Integer value2) {
			addCriterion("num2 between", value1, value2, "num2");
			return (Criteria) this;
		}

		public Criteria andNum2NotBetween(Integer value1, Integer value2) {
			addCriterion("num2 not between", value1, value2, "num2");
			return (Criteria) this;
		}

		public Criteria andNum3IsNull() {
			addCriterion("num3 is null");
			return (Criteria) this;
		}

		public Criteria andNum3IsNotNull() {
			addCriterion("num3 is not null");
			return (Criteria) this;
		}

		public Criteria andNum3EqualTo(Integer value) {
			addCriterion("num3 =", value, "num3");
			return (Criteria) this;
		}

		public Criteria andNum3NotEqualTo(Integer value) {
			addCriterion("num3 <>", value, "num3");
			return (Criteria) this;
		}

		public Criteria andNum3GreaterThan(Integer value) {
			addCriterion("num3 >", value, "num3");
			return (Criteria) this;
		}

		public Criteria andNum3GreaterThanOrEqualTo(Integer value) {
			addCriterion("num3 >=", value, "num3");
			return (Criteria) this;
		}

		public Criteria andNum3LessThan(Integer value) {
			addCriterion("num3 <", value, "num3");
			return (Criteria) this;
		}

		public Criteria andNum3LessThanOrEqualTo(Integer value) {
			addCriterion("num3 <=", value, "num3");
			return (Criteria) this;
		}

		public Criteria andNum3In(List<Integer> values) {
			addCriterion("num3 in", values, "num3");
			return (Criteria) this;
		}

		public Criteria andNum3NotIn(List<Integer> values) {
			addCriterion("num3 not in", values, "num3");
			return (Criteria) this;
		}

		public Criteria andNum3Between(Integer value1, Integer value2) {
			addCriterion("num3 between", value1, value2, "num3");
			return (Criteria) this;
		}

		public Criteria andNum3NotBetween(Integer value1, Integer value2) {
			addCriterion("num3 not between", value1, value2, "num3");
			return (Criteria) this;
		}

		public Criteria andNum_shosuari1IsNull() {
			addCriterion("num_shosuari1 is null");
			return (Criteria) this;
		}

		public Criteria andNum_shosuari1IsNotNull() {
			addCriterion("num_shosuari1 is not null");
			return (Criteria) this;
		}

		public Criteria andNum_shosuari1EqualTo(BigDecimal value) {
			addCriterion("num_shosuari1 =", value, "num_shosuari1");
			return (Criteria) this;
		}

		public Criteria andNum_shosuari1NotEqualTo(BigDecimal value) {
			addCriterion("num_shosuari1 <>", value, "num_shosuari1");
			return (Criteria) this;
		}

		public Criteria andNum_shosuari1GreaterThan(BigDecimal value) {
			addCriterion("num_shosuari1 >", value, "num_shosuari1");
			return (Criteria) this;
		}

		public Criteria andNum_shosuari1GreaterThanOrEqualTo(BigDecimal value) {
			addCriterion("num_shosuari1 >=", value, "num_shosuari1");
			return (Criteria) this;
		}

		public Criteria andNum_shosuari1LessThan(BigDecimal value) {
			addCriterion("num_shosuari1 <", value, "num_shosuari1");
			return (Criteria) this;
		}

		public Criteria andNum_shosuari1LessThanOrEqualTo(BigDecimal value) {
			addCriterion("num_shosuari1 <=", value, "num_shosuari1");
			return (Criteria) this;
		}

		public Criteria andNum_shosuari1In(List<BigDecimal> values) {
			addCriterion("num_shosuari1 in", values, "num_shosuari1");
			return (Criteria) this;
		}

		public Criteria andNum_shosuari1NotIn(List<BigDecimal> values) {
			addCriterion("num_shosuari1 not in", values, "num_shosuari1");
			return (Criteria) this;
		}

		public Criteria andNum_shosuari1Between(BigDecimal value1, BigDecimal value2) {
			addCriterion("num_shosuari1 between", value1, value2, "num_shosuari1");
			return (Criteria) this;
		}

		public Criteria andNum_shosuari1NotBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("num_shosuari1 not between", value1, value2, "num_shosuari1");
			return (Criteria) this;
		}

		public Criteria andNum_shosuari2IsNull() {
			addCriterion("num_shosuari2 is null");
			return (Criteria) this;
		}

		public Criteria andNum_shosuari2IsNotNull() {
			addCriterion("num_shosuari2 is not null");
			return (Criteria) this;
		}

		public Criteria andNum_shosuari2EqualTo(BigDecimal value) {
			addCriterion("num_shosuari2 =", value, "num_shosuari2");
			return (Criteria) this;
		}

		public Criteria andNum_shosuari2NotEqualTo(BigDecimal value) {
			addCriterion("num_shosuari2 <>", value, "num_shosuari2");
			return (Criteria) this;
		}

		public Criteria andNum_shosuari2GreaterThan(BigDecimal value) {
			addCriterion("num_shosuari2 >", value, "num_shosuari2");
			return (Criteria) this;
		}

		public Criteria andNum_shosuari2GreaterThanOrEqualTo(BigDecimal value) {
			addCriterion("num_shosuari2 >=", value, "num_shosuari2");
			return (Criteria) this;
		}

		public Criteria andNum_shosuari2LessThan(BigDecimal value) {
			addCriterion("num_shosuari2 <", value, "num_shosuari2");
			return (Criteria) this;
		}

		public Criteria andNum_shosuari2LessThanOrEqualTo(BigDecimal value) {
			addCriterion("num_shosuari2 <=", value, "num_shosuari2");
			return (Criteria) this;
		}

		public Criteria andNum_shosuari2In(List<BigDecimal> values) {
			addCriterion("num_shosuari2 in", values, "num_shosuari2");
			return (Criteria) this;
		}

		public Criteria andNum_shosuari2NotIn(List<BigDecimal> values) {
			addCriterion("num_shosuari2 not in", values, "num_shosuari2");
			return (Criteria) this;
		}

		public Criteria andNum_shosuari2Between(BigDecimal value1, BigDecimal value2) {
			addCriterion("num_shosuari2 between", value1, value2, "num_shosuari2");
			return (Criteria) this;
		}

		public Criteria andNum_shosuari2NotBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("num_shosuari2 not between", value1, value2, "num_shosuari2");
			return (Criteria) this;
		}

		public Criteria andNum_shosuari3IsNull() {
			addCriterion("num_shosuari3 is null");
			return (Criteria) this;
		}

		public Criteria andNum_shosuari3IsNotNull() {
			addCriterion("num_shosuari3 is not null");
			return (Criteria) this;
		}

		public Criteria andNum_shosuari3EqualTo(BigDecimal value) {
			addCriterion("num_shosuari3 =", value, "num_shosuari3");
			return (Criteria) this;
		}

		public Criteria andNum_shosuari3NotEqualTo(BigDecimal value) {
			addCriterion("num_shosuari3 <>", value, "num_shosuari3");
			return (Criteria) this;
		}

		public Criteria andNum_shosuari3GreaterThan(BigDecimal value) {
			addCriterion("num_shosuari3 >", value, "num_shosuari3");
			return (Criteria) this;
		}

		public Criteria andNum_shosuari3GreaterThanOrEqualTo(BigDecimal value) {
			addCriterion("num_shosuari3 >=", value, "num_shosuari3");
			return (Criteria) this;
		}

		public Criteria andNum_shosuari3LessThan(BigDecimal value) {
			addCriterion("num_shosuari3 <", value, "num_shosuari3");
			return (Criteria) this;
		}

		public Criteria andNum_shosuari3LessThanOrEqualTo(BigDecimal value) {
			addCriterion("num_shosuari3 <=", value, "num_shosuari3");
			return (Criteria) this;
		}

		public Criteria andNum_shosuari3In(List<BigDecimal> values) {
			addCriterion("num_shosuari3 in", values, "num_shosuari3");
			return (Criteria) this;
		}

		public Criteria andNum_shosuari3NotIn(List<BigDecimal> values) {
			addCriterion("num_shosuari3 not in", values, "num_shosuari3");
			return (Criteria) this;
		}

		public Criteria andNum_shosuari3Between(BigDecimal value1, BigDecimal value2) {
			addCriterion("num_shosuari3 between", value1, value2, "num_shosuari3");
			return (Criteria) this;
		}

		public Criteria andNum_shosuari3NotBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("num_shosuari3 not between", value1, value2, "num_shosuari3");
			return (Criteria) this;
		}

		public Criteria andHyojijun1IsNull() {
			addCriterion("hyojijun1 is null");
			return (Criteria) this;
		}

		public Criteria andHyojijun1IsNotNull() {
			addCriterion("hyojijun1 is not null");
			return (Criteria) this;
		}

		public Criteria andHyojijun1EqualTo(Integer value) {
			addCriterion("hyojijun1 =", value, "hyojijun1");
			return (Criteria) this;
		}

		public Criteria andHyojijun1NotEqualTo(Integer value) {
			addCriterion("hyojijun1 <>", value, "hyojijun1");
			return (Criteria) this;
		}

		public Criteria andHyojijun1GreaterThan(Integer value) {
			addCriterion("hyojijun1 >", value, "hyojijun1");
			return (Criteria) this;
		}

		public Criteria andHyojijun1GreaterThanOrEqualTo(Integer value) {
			addCriterion("hyojijun1 >=", value, "hyojijun1");
			return (Criteria) this;
		}

		public Criteria andHyojijun1LessThan(Integer value) {
			addCriterion("hyojijun1 <", value, "hyojijun1");
			return (Criteria) this;
		}

		public Criteria andHyojijun1LessThanOrEqualTo(Integer value) {
			addCriterion("hyojijun1 <=", value, "hyojijun1");
			return (Criteria) this;
		}

		public Criteria andHyojijun1In(List<Integer> values) {
			addCriterion("hyojijun1 in", values, "hyojijun1");
			return (Criteria) this;
		}

		public Criteria andHyojijun1NotIn(List<Integer> values) {
			addCriterion("hyojijun1 not in", values, "hyojijun1");
			return (Criteria) this;
		}

		public Criteria andHyojijun1Between(Integer value1, Integer value2) {
			addCriterion("hyojijun1 between", value1, value2, "hyojijun1");
			return (Criteria) this;
		}

		public Criteria andHyojijun1NotBetween(Integer value1, Integer value2) {
			addCriterion("hyojijun1 not between", value1, value2, "hyojijun1");
			return (Criteria) this;
		}

		public Criteria andHyojijun2IsNull() {
			addCriterion("hyojijun2 is null");
			return (Criteria) this;
		}

		public Criteria andHyojijun2IsNotNull() {
			addCriterion("hyojijun2 is not null");
			return (Criteria) this;
		}

		public Criteria andHyojijun2EqualTo(Integer value) {
			addCriterion("hyojijun2 =", value, "hyojijun2");
			return (Criteria) this;
		}

		public Criteria andHyojijun2NotEqualTo(Integer value) {
			addCriterion("hyojijun2 <>", value, "hyojijun2");
			return (Criteria) this;
		}

		public Criteria andHyojijun2GreaterThan(Integer value) {
			addCriterion("hyojijun2 >", value, "hyojijun2");
			return (Criteria) this;
		}

		public Criteria andHyojijun2GreaterThanOrEqualTo(Integer value) {
			addCriterion("hyojijun2 >=", value, "hyojijun2");
			return (Criteria) this;
		}

		public Criteria andHyojijun2LessThan(Integer value) {
			addCriterion("hyojijun2 <", value, "hyojijun2");
			return (Criteria) this;
		}

		public Criteria andHyojijun2LessThanOrEqualTo(Integer value) {
			addCriterion("hyojijun2 <=", value, "hyojijun2");
			return (Criteria) this;
		}

		public Criteria andHyojijun2In(List<Integer> values) {
			addCriterion("hyojijun2 in", values, "hyojijun2");
			return (Criteria) this;
		}

		public Criteria andHyojijun2NotIn(List<Integer> values) {
			addCriterion("hyojijun2 not in", values, "hyojijun2");
			return (Criteria) this;
		}

		public Criteria andHyojijun2Between(Integer value1, Integer value2) {
			addCriterion("hyojijun2 between", value1, value2, "hyojijun2");
			return (Criteria) this;
		}

		public Criteria andHyojijun2NotBetween(Integer value1, Integer value2) {
			addCriterion("hyojijun2 not between", value1, value2, "hyojijun2");
			return (Criteria) this;
		}

		public Criteria andHyojijun3IsNull() {
			addCriterion("hyojijun3 is null");
			return (Criteria) this;
		}

		public Criteria andHyojijun3IsNotNull() {
			addCriterion("hyojijun3 is not null");
			return (Criteria) this;
		}

		public Criteria andHyojijun3EqualTo(Integer value) {
			addCriterion("hyojijun3 =", value, "hyojijun3");
			return (Criteria) this;
		}

		public Criteria andHyojijun3NotEqualTo(Integer value) {
			addCriterion("hyojijun3 <>", value, "hyojijun3");
			return (Criteria) this;
		}

		public Criteria andHyojijun3GreaterThan(Integer value) {
			addCriterion("hyojijun3 >", value, "hyojijun3");
			return (Criteria) this;
		}

		public Criteria andHyojijun3GreaterThanOrEqualTo(Integer value) {
			addCriterion("hyojijun3 >=", value, "hyojijun3");
			return (Criteria) this;
		}

		public Criteria andHyojijun3LessThan(Integer value) {
			addCriterion("hyojijun3 <", value, "hyojijun3");
			return (Criteria) this;
		}

		public Criteria andHyojijun3LessThanOrEqualTo(Integer value) {
			addCriterion("hyojijun3 <=", value, "hyojijun3");
			return (Criteria) this;
		}

		public Criteria andHyojijun3In(List<Integer> values) {
			addCriterion("hyojijun3 in", values, "hyojijun3");
			return (Criteria) this;
		}

		public Criteria andHyojijun3NotIn(List<Integer> values) {
			addCriterion("hyojijun3 not in", values, "hyojijun3");
			return (Criteria) this;
		}

		public Criteria andHyojijun3Between(Integer value1, Integer value2) {
			addCriterion("hyojijun3 between", value1, value2, "hyojijun3");
			return (Criteria) this;
		}

		public Criteria andHyojijun3NotBetween(Integer value1, Integer value2) {
			addCriterion("hyojijun3 not between", value1, value2, "hyojijun3");
			return (Criteria) this;
		}

		public Criteria andHanyo_bikoIsNull() {
			addCriterion("hanyo_biko is null");
			return (Criteria) this;
		}

		public Criteria andHanyo_bikoIsNotNull() {
			addCriterion("hanyo_biko is not null");
			return (Criteria) this;
		}

		public Criteria andHanyo_bikoEqualTo(String value) {
			addCriterion("hanyo_biko =", value, "hanyo_biko");
			return (Criteria) this;
		}

		public Criteria andHanyo_bikoNotEqualTo(String value) {
			addCriterion("hanyo_biko <>", value, "hanyo_biko");
			return (Criteria) this;
		}

		public Criteria andHanyo_bikoGreaterThan(String value) {
			addCriterion("hanyo_biko >", value, "hanyo_biko");
			return (Criteria) this;
		}

		public Criteria andHanyo_bikoGreaterThanOrEqualTo(String value) {
			addCriterion("hanyo_biko >=", value, "hanyo_biko");
			return (Criteria) this;
		}

		public Criteria andHanyo_bikoLessThan(String value) {
			addCriterion("hanyo_biko <", value, "hanyo_biko");
			return (Criteria) this;
		}

		public Criteria andHanyo_bikoLessThanOrEqualTo(String value) {
			addCriterion("hanyo_biko <=", value, "hanyo_biko");
			return (Criteria) this;
		}

		public Criteria andHanyo_bikoLike(String value) {
			addCriterion("hanyo_biko like", value, "hanyo_biko");
			return (Criteria) this;
		}

		public Criteria andHanyo_bikoNotLike(String value) {
			addCriterion("hanyo_biko not like", value, "hanyo_biko");
			return (Criteria) this;
		}

		public Criteria andHanyo_bikoIn(List<String> values) {
			addCriterion("hanyo_biko in", values, "hanyo_biko");
			return (Criteria) this;
		}

		public Criteria andHanyo_bikoNotIn(List<String> values) {
			addCriterion("hanyo_biko not in", values, "hanyo_biko");
			return (Criteria) this;
		}

		public Criteria andHanyo_bikoBetween(String value1, String value2) {
			addCriterion("hanyo_biko between", value1, value2, "hanyo_biko");
			return (Criteria) this;
		}

		public Criteria andHanyo_bikoNotBetween(String value1, String value2) {
			addCriterion("hanyo_biko not between", value1, value2, "hanyo_biko");
			return (Criteria) this;
		}

		public Criteria andTekiyoend_ymdIsNull() {
			addCriterion("tekiyoend_ymd is null");
			return (Criteria) this;
		}

		public Criteria andTekiyoend_ymdIsNotNull() {
			addCriterion("tekiyoend_ymd is not null");
			return (Criteria) this;
		}

		public Criteria andTekiyoend_ymdEqualTo(Date value) {
			addCriterionForJDBCDate("tekiyoend_ymd =", value, "tekiyoend_ymd");
			return (Criteria) this;
		}

		public Criteria andTekiyoend_ymdNotEqualTo(Date value) {
			addCriterionForJDBCDate("tekiyoend_ymd <>", value, "tekiyoend_ymd");
			return (Criteria) this;
		}

		public Criteria andTekiyoend_ymdGreaterThan(Date value) {
			addCriterionForJDBCDate("tekiyoend_ymd >", value, "tekiyoend_ymd");
			return (Criteria) this;
		}

		public Criteria andTekiyoend_ymdGreaterThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("tekiyoend_ymd >=", value, "tekiyoend_ymd");
			return (Criteria) this;
		}

		public Criteria andTekiyoend_ymdLessThan(Date value) {
			addCriterionForJDBCDate("tekiyoend_ymd <", value, "tekiyoend_ymd");
			return (Criteria) this;
		}

		public Criteria andTekiyoend_ymdLessThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("tekiyoend_ymd <=", value, "tekiyoend_ymd");
			return (Criteria) this;
		}

		public Criteria andTekiyoend_ymdIn(List<Date> values) {
			addCriterionForJDBCDate("tekiyoend_ymd in", values, "tekiyoend_ymd");
			return (Criteria) this;
		}

		public Criteria andTekiyoend_ymdNotIn(List<Date> values) {
			addCriterionForJDBCDate("tekiyoend_ymd not in", values, "tekiyoend_ymd");
			return (Criteria) this;
		}

		public Criteria andTekiyoend_ymdBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("tekiyoend_ymd between", value1, value2, "tekiyoend_ymd");
			return (Criteria) this;
		}

		public Criteria andTekiyoend_ymdNotBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("tekiyoend_ymd not between", value1, value2, "tekiyoend_ymd");
			return (Criteria) this;
		}

		public Criteria andVersionIsNull() {
			addCriterion("version is null");
			return (Criteria) this;
		}

		public Criteria andVersionIsNotNull() {
			addCriterion("version is not null");
			return (Criteria) this;
		}

		public Criteria andVersionEqualTo(Integer value) {
			addCriterion("version =", value, "version");
			return (Criteria) this;
		}

		public Criteria andVersionNotEqualTo(Integer value) {
			addCriterion("version <>", value, "version");
			return (Criteria) this;
		}

		public Criteria andVersionGreaterThan(Integer value) {
			addCriterion("version >", value, "version");
			return (Criteria) this;
		}

		public Criteria andVersionGreaterThanOrEqualTo(Integer value) {
			addCriterion("version >=", value, "version");
			return (Criteria) this;
		}

		public Criteria andVersionLessThan(Integer value) {
			addCriterion("version <", value, "version");
			return (Criteria) this;
		}

		public Criteria andVersionLessThanOrEqualTo(Integer value) {
			addCriterion("version <=", value, "version");
			return (Criteria) this;
		}

		public Criteria andVersionIn(List<Integer> values) {
			addCriterion("version in", values, "version");
			return (Criteria) this;
		}

		public Criteria andVersionNotIn(List<Integer> values) {
			addCriterion("version not in", values, "version");
			return (Criteria) this;
		}

		public Criteria andVersionBetween(Integer value1, Integer value2) {
			addCriterion("version between", value1, value2, "version");
			return (Criteria) this;
		}

		public Criteria andVersionNotBetween(Integer value1, Integer value2) {
			addCriterion("version not between", value1, value2, "version");
			return (Criteria) this;
		}

		public Criteria andCrt_ymdhmsIsNull() {
			addCriterion("crt_ymdhms is null");
			return (Criteria) this;
		}

		public Criteria andCrt_ymdhmsIsNotNull() {
			addCriterion("crt_ymdhms is not null");
			return (Criteria) this;
		}

		public Criteria andCrt_ymdhmsEqualTo(Date value) {
			addCriterion("crt_ymdhms =", value, "crt_ymdhms");
			return (Criteria) this;
		}

		public Criteria andCrt_ymdhmsNotEqualTo(Date value) {
			addCriterion("crt_ymdhms <>", value, "crt_ymdhms");
			return (Criteria) this;
		}

		public Criteria andCrt_ymdhmsGreaterThan(Date value) {
			addCriterion("crt_ymdhms >", value, "crt_ymdhms");
			return (Criteria) this;
		}

		public Criteria andCrt_ymdhmsGreaterThanOrEqualTo(Date value) {
			addCriterion("crt_ymdhms >=", value, "crt_ymdhms");
			return (Criteria) this;
		}

		public Criteria andCrt_ymdhmsLessThan(Date value) {
			addCriterion("crt_ymdhms <", value, "crt_ymdhms");
			return (Criteria) this;
		}

		public Criteria andCrt_ymdhmsLessThanOrEqualTo(Date value) {
			addCriterion("crt_ymdhms <=", value, "crt_ymdhms");
			return (Criteria) this;
		}

		public Criteria andCrt_ymdhmsIn(List<Date> values) {
			addCriterion("crt_ymdhms in", values, "crt_ymdhms");
			return (Criteria) this;
		}

		public Criteria andCrt_ymdhmsNotIn(List<Date> values) {
			addCriterion("crt_ymdhms not in", values, "crt_ymdhms");
			return (Criteria) this;
		}

		public Criteria andCrt_ymdhmsBetween(Date value1, Date value2) {
			addCriterion("crt_ymdhms between", value1, value2, "crt_ymdhms");
			return (Criteria) this;
		}

		public Criteria andCrt_ymdhmsNotBetween(Date value1, Date value2) {
			addCriterion("crt_ymdhms not between", value1, value2, "crt_ymdhms");
			return (Criteria) this;
		}

		public Criteria andCrtshain_codIsNull() {
			addCriterion("crtshain_cod is null");
			return (Criteria) this;
		}

		public Criteria andCrtshain_codIsNotNull() {
			addCriterion("crtshain_cod is not null");
			return (Criteria) this;
		}

		public Criteria andCrtshain_codEqualTo(String value) {
			addCriterion("crtshain_cod =", value, "crtshain_cod");
			return (Criteria) this;
		}

		public Criteria andCrtshain_codNotEqualTo(String value) {
			addCriterion("crtshain_cod <>", value, "crtshain_cod");
			return (Criteria) this;
		}

		public Criteria andCrtshain_codGreaterThan(String value) {
			addCriterion("crtshain_cod >", value, "crtshain_cod");
			return (Criteria) this;
		}

		public Criteria andCrtshain_codGreaterThanOrEqualTo(String value) {
			addCriterion("crtshain_cod >=", value, "crtshain_cod");
			return (Criteria) this;
		}

		public Criteria andCrtshain_codLessThan(String value) {
			addCriterion("crtshain_cod <", value, "crtshain_cod");
			return (Criteria) this;
		}

		public Criteria andCrtshain_codLessThanOrEqualTo(String value) {
			addCriterion("crtshain_cod <=", value, "crtshain_cod");
			return (Criteria) this;
		}

		public Criteria andCrtshain_codLike(String value) {
			addCriterion("crtshain_cod like", value, "crtshain_cod");
			return (Criteria) this;
		}

		public Criteria andCrtshain_codNotLike(String value) {
			addCriterion("crtshain_cod not like", value, "crtshain_cod");
			return (Criteria) this;
		}

		public Criteria andCrtshain_codIn(List<String> values) {
			addCriterion("crtshain_cod in", values, "crtshain_cod");
			return (Criteria) this;
		}

		public Criteria andCrtshain_codNotIn(List<String> values) {
			addCriterion("crtshain_cod not in", values, "crtshain_cod");
			return (Criteria) this;
		}

		public Criteria andCrtshain_codBetween(String value1, String value2) {
			addCriterion("crtshain_cod between", value1, value2, "crtshain_cod");
			return (Criteria) this;
		}

		public Criteria andCrtshain_codNotBetween(String value1, String value2) {
			addCriterion("crtshain_cod not between", value1, value2, "crtshain_cod");
			return (Criteria) this;
		}

		public Criteria andCrt_func_idIsNull() {
			addCriterion("crt_func_id is null");
			return (Criteria) this;
		}

		public Criteria andCrt_func_idIsNotNull() {
			addCriterion("crt_func_id is not null");
			return (Criteria) this;
		}

		public Criteria andCrt_func_idEqualTo(String value) {
			addCriterion("crt_func_id =", value, "crt_func_id");
			return (Criteria) this;
		}

		public Criteria andCrt_func_idNotEqualTo(String value) {
			addCriterion("crt_func_id <>", value, "crt_func_id");
			return (Criteria) this;
		}

		public Criteria andCrt_func_idGreaterThan(String value) {
			addCriterion("crt_func_id >", value, "crt_func_id");
			return (Criteria) this;
		}

		public Criteria andCrt_func_idGreaterThanOrEqualTo(String value) {
			addCriterion("crt_func_id >=", value, "crt_func_id");
			return (Criteria) this;
		}

		public Criteria andCrt_func_idLessThan(String value) {
			addCriterion("crt_func_id <", value, "crt_func_id");
			return (Criteria) this;
		}

		public Criteria andCrt_func_idLessThanOrEqualTo(String value) {
			addCriterion("crt_func_id <=", value, "crt_func_id");
			return (Criteria) this;
		}

		public Criteria andCrt_func_idLike(String value) {
			addCriterion("crt_func_id like", value, "crt_func_id");
			return (Criteria) this;
		}

		public Criteria andCrt_func_idNotLike(String value) {
			addCriterion("crt_func_id not like", value, "crt_func_id");
			return (Criteria) this;
		}

		public Criteria andCrt_func_idIn(List<String> values) {
			addCriterion("crt_func_id in", values, "crt_func_id");
			return (Criteria) this;
		}

		public Criteria andCrt_func_idNotIn(List<String> values) {
			addCriterion("crt_func_id not in", values, "crt_func_id");
			return (Criteria) this;
		}

		public Criteria andCrt_func_idBetween(String value1, String value2) {
			addCriterion("crt_func_id between", value1, value2, "crt_func_id");
			return (Criteria) this;
		}

		public Criteria andCrt_func_idNotBetween(String value1, String value2) {
			addCriterion("crt_func_id not between", value1, value2, "crt_func_id");
			return (Criteria) this;
		}

		public Criteria andUpd_ymdhmsIsNull() {
			addCriterion("upd_ymdhms is null");
			return (Criteria) this;
		}

		public Criteria andUpd_ymdhmsIsNotNull() {
			addCriterion("upd_ymdhms is not null");
			return (Criteria) this;
		}

		public Criteria andUpd_ymdhmsEqualTo(Date value) {
			addCriterion("upd_ymdhms =", value, "upd_ymdhms");
			return (Criteria) this;
		}

		public Criteria andUpd_ymdhmsNotEqualTo(Date value) {
			addCriterion("upd_ymdhms <>", value, "upd_ymdhms");
			return (Criteria) this;
		}

		public Criteria andUpd_ymdhmsGreaterThan(Date value) {
			addCriterion("upd_ymdhms >", value, "upd_ymdhms");
			return (Criteria) this;
		}

		public Criteria andUpd_ymdhmsGreaterThanOrEqualTo(Date value) {
			addCriterion("upd_ymdhms >=", value, "upd_ymdhms");
			return (Criteria) this;
		}

		public Criteria andUpd_ymdhmsLessThan(Date value) {
			addCriterion("upd_ymdhms <", value, "upd_ymdhms");
			return (Criteria) this;
		}

		public Criteria andUpd_ymdhmsLessThanOrEqualTo(Date value) {
			addCriterion("upd_ymdhms <=", value, "upd_ymdhms");
			return (Criteria) this;
		}

		public Criteria andUpd_ymdhmsIn(List<Date> values) {
			addCriterion("upd_ymdhms in", values, "upd_ymdhms");
			return (Criteria) this;
		}

		public Criteria andUpd_ymdhmsNotIn(List<Date> values) {
			addCriterion("upd_ymdhms not in", values, "upd_ymdhms");
			return (Criteria) this;
		}

		public Criteria andUpd_ymdhmsBetween(Date value1, Date value2) {
			addCriterion("upd_ymdhms between", value1, value2, "upd_ymdhms");
			return (Criteria) this;
		}

		public Criteria andUpd_ymdhmsNotBetween(Date value1, Date value2) {
			addCriterion("upd_ymdhms not between", value1, value2, "upd_ymdhms");
			return (Criteria) this;
		}

		public Criteria andUpdshain_codIsNull() {
			addCriterion("updshain_cod is null");
			return (Criteria) this;
		}

		public Criteria andUpdshain_codIsNotNull() {
			addCriterion("updshain_cod is not null");
			return (Criteria) this;
		}

		public Criteria andUpdshain_codEqualTo(String value) {
			addCriterion("updshain_cod =", value, "updshain_cod");
			return (Criteria) this;
		}

		public Criteria andUpdshain_codNotEqualTo(String value) {
			addCriterion("updshain_cod <>", value, "updshain_cod");
			return (Criteria) this;
		}

		public Criteria andUpdshain_codGreaterThan(String value) {
			addCriterion("updshain_cod >", value, "updshain_cod");
			return (Criteria) this;
		}

		public Criteria andUpdshain_codGreaterThanOrEqualTo(String value) {
			addCriterion("updshain_cod >=", value, "updshain_cod");
			return (Criteria) this;
		}

		public Criteria andUpdshain_codLessThan(String value) {
			addCriterion("updshain_cod <", value, "updshain_cod");
			return (Criteria) this;
		}

		public Criteria andUpdshain_codLessThanOrEqualTo(String value) {
			addCriterion("updshain_cod <=", value, "updshain_cod");
			return (Criteria) this;
		}

		public Criteria andUpdshain_codLike(String value) {
			addCriterion("updshain_cod like", value, "updshain_cod");
			return (Criteria) this;
		}

		public Criteria andUpdshain_codNotLike(String value) {
			addCriterion("updshain_cod not like", value, "updshain_cod");
			return (Criteria) this;
		}

		public Criteria andUpdshain_codIn(List<String> values) {
			addCriterion("updshain_cod in", values, "updshain_cod");
			return (Criteria) this;
		}

		public Criteria andUpdshain_codNotIn(List<String> values) {
			addCriterion("updshain_cod not in", values, "updshain_cod");
			return (Criteria) this;
		}

		public Criteria andUpdshain_codBetween(String value1, String value2) {
			addCriterion("updshain_cod between", value1, value2, "updshain_cod");
			return (Criteria) this;
		}

		public Criteria andUpdshain_codNotBetween(String value1, String value2) {
			addCriterion("updshain_cod not between", value1, value2, "updshain_cod");
			return (Criteria) this;
		}

		public Criteria andUpd_func_idIsNull() {
			addCriterion("upd_func_id is null");
			return (Criteria) this;
		}

		public Criteria andUpd_func_idIsNotNull() {
			addCriterion("upd_func_id is not null");
			return (Criteria) this;
		}

		public Criteria andUpd_func_idEqualTo(String value) {
			addCriterion("upd_func_id =", value, "upd_func_id");
			return (Criteria) this;
		}

		public Criteria andUpd_func_idNotEqualTo(String value) {
			addCriterion("upd_func_id <>", value, "upd_func_id");
			return (Criteria) this;
		}

		public Criteria andUpd_func_idGreaterThan(String value) {
			addCriterion("upd_func_id >", value, "upd_func_id");
			return (Criteria) this;
		}

		public Criteria andUpd_func_idGreaterThanOrEqualTo(String value) {
			addCriterion("upd_func_id >=", value, "upd_func_id");
			return (Criteria) this;
		}

		public Criteria andUpd_func_idLessThan(String value) {
			addCriterion("upd_func_id <", value, "upd_func_id");
			return (Criteria) this;
		}

		public Criteria andUpd_func_idLessThanOrEqualTo(String value) {
			addCriterion("upd_func_id <=", value, "upd_func_id");
			return (Criteria) this;
		}

		public Criteria andUpd_func_idLike(String value) {
			addCriterion("upd_func_id like", value, "upd_func_id");
			return (Criteria) this;
		}

		public Criteria andUpd_func_idNotLike(String value) {
			addCriterion("upd_func_id not like", value, "upd_func_id");
			return (Criteria) this;
		}

		public Criteria andUpd_func_idIn(List<String> values) {
			addCriterion("upd_func_id in", values, "upd_func_id");
			return (Criteria) this;
		}

		public Criteria andUpd_func_idNotIn(List<String> values) {
			addCriterion("upd_func_id not in", values, "upd_func_id");
			return (Criteria) this;
		}

		public Criteria andUpd_func_idBetween(String value1, String value2) {
			addCriterion("upd_func_id between", value1, value2, "upd_func_id");
			return (Criteria) this;
		}

		public Criteria andUpd_func_idNotBetween(String value1, String value2) {
			addCriterion("upd_func_id not between", value1, value2, "upd_func_id");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table tmhanyo
	 * @mbg.generated  Sun Sep 18 16:27:33 CST 2022
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tmhanyo
     *
     * @mbg.generated do_not_delete_during_merge Sat Sep 17 23:59:59 CST 2022
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }
}