package com.wetech.ryutsumodel.model.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class TmmbumonnayosemiExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table tmmbumonnayosemi
	 * @mbg.generated  Fri Nov 11 16:38:00 JST 2022
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table tmmbumonnayosemi
	 * @mbg.generated  Fri Nov 11 16:38:00 JST 2022
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table tmmbumonnayosemi
	 * @mbg.generated  Fri Nov 11 16:38:00 JST 2022
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tmmbumonnayosemi
	 * @mbg.generated  Fri Nov 11 16:38:00 JST 2022
	 */
	public TmmbumonnayosemiExample() {
		oredCriteria = new ArrayList<>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tmmbumonnayosemi
	 * @mbg.generated  Fri Nov 11 16:38:00 JST 2022
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tmmbumonnayosemi
	 * @mbg.generated  Fri Nov 11 16:38:00 JST 2022
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tmmbumonnayosemi
	 * @mbg.generated  Fri Nov 11 16:38:00 JST 2022
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tmmbumonnayosemi
	 * @mbg.generated  Fri Nov 11 16:38:00 JST 2022
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tmmbumonnayosemi
	 * @mbg.generated  Fri Nov 11 16:38:00 JST 2022
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tmmbumonnayosemi
	 * @mbg.generated  Fri Nov 11 16:38:00 JST 2022
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tmmbumonnayosemi
	 * @mbg.generated  Fri Nov 11 16:38:00 JST 2022
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tmmbumonnayosemi
	 * @mbg.generated  Fri Nov 11 16:38:00 JST 2022
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tmmbumonnayosemi
	 * @mbg.generated  Fri Nov 11 16:38:00 JST 2022
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tmmbumonnayosemi
	 * @mbg.generated  Fri Nov 11 16:38:00 JST 2022
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table tmmbumonnayosemi
	 * @mbg.generated  Fri Nov 11 16:38:00 JST 2022
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		protected void addCriterionForJDBCDate(String condition, Date value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			addCriterion(condition, new java.sql.Date(value.getTime()), property);
		}

		protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
			if (values == null || values.size() == 0) {
				throw new RuntimeException("Value list for " + property + " cannot be null or empty");
			}
			List<java.sql.Date> dateList = new ArrayList<>();
			Iterator<Date> iter = values.iterator();
			while (iter.hasNext()) {
				dateList.add(new java.sql.Date(iter.next().getTime()));
			}
			addCriterion(condition, dateList, property);
		}

		protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
		}

		public Criteria andJcmsaimutegataKbnIsNull() {
			addCriterion("jcmsaimutegata_kbn is null");
			return (Criteria) this;
		}

		public Criteria andJcmsaimutegataKbnIsNotNull() {
			addCriterion("jcmsaimutegata_kbn is not null");
			return (Criteria) this;
		}

		public Criteria andJcmsaimutegataKbnEqualTo(String value) {
			addCriterion("jcmsaimutegata_kbn =", value, "jcmsaimutegataKbn");
			return (Criteria) this;
		}

		public Criteria andJcmsaimutegataKbnNotEqualTo(String value) {
			addCriterion("jcmsaimutegata_kbn <>", value, "jcmsaimutegataKbn");
			return (Criteria) this;
		}

		public Criteria andJcmsaimutegataKbnGreaterThan(String value) {
			addCriterion("jcmsaimutegata_kbn >", value, "jcmsaimutegataKbn");
			return (Criteria) this;
		}

		public Criteria andJcmsaimutegataKbnGreaterThanOrEqualTo(String value) {
			addCriterion("jcmsaimutegata_kbn >=", value, "jcmsaimutegataKbn");
			return (Criteria) this;
		}

		public Criteria andJcmsaimutegataKbnLessThan(String value) {
			addCriterion("jcmsaimutegata_kbn <", value, "jcmsaimutegataKbn");
			return (Criteria) this;
		}

		public Criteria andJcmsaimutegataKbnLessThanOrEqualTo(String value) {
			addCriterion("jcmsaimutegata_kbn <=", value, "jcmsaimutegataKbn");
			return (Criteria) this;
		}

		public Criteria andJcmsaimutegataKbnLike(String value) {
			addCriterion("jcmsaimutegata_kbn like", value, "jcmsaimutegataKbn");
			return (Criteria) this;
		}

		public Criteria andJcmsaimutegataKbnNotLike(String value) {
			addCriterion("jcmsaimutegata_kbn not like", value, "jcmsaimutegataKbn");
			return (Criteria) this;
		}

		public Criteria andJcmsaimutegataKbnIn(List<String> values) {
			addCriterion("jcmsaimutegata_kbn in", values, "jcmsaimutegataKbn");
			return (Criteria) this;
		}

		public Criteria andJcmsaimutegataKbnNotIn(List<String> values) {
			addCriterion("jcmsaimutegata_kbn not in", values, "jcmsaimutegataKbn");
			return (Criteria) this;
		}

		public Criteria andJcmsaimutegataKbnBetween(String value1, String value2) {
			addCriterion("jcmsaimutegata_kbn between", value1, value2, "jcmsaimutegataKbn");
			return (Criteria) this;
		}

		public Criteria andJcmsaimutegataKbnNotBetween(String value1, String value2) {
			addCriterion("jcmsaimutegata_kbn not between", value1, value2, "jcmsaimutegataKbn");
			return (Criteria) this;
		}

		public Criteria andJcmnayosekanriCodIsNull() {
			addCriterion("jcmnayosekanri_cod is null");
			return (Criteria) this;
		}

		public Criteria andJcmnayosekanriCodIsNotNull() {
			addCriterion("jcmnayosekanri_cod is not null");
			return (Criteria) this;
		}

		public Criteria andJcmnayosekanriCodEqualTo(String value) {
			addCriterion("jcmnayosekanri_cod =", value, "jcmnayosekanriCod");
			return (Criteria) this;
		}

		public Criteria andJcmnayosekanriCodNotEqualTo(String value) {
			addCriterion("jcmnayosekanri_cod <>", value, "jcmnayosekanriCod");
			return (Criteria) this;
		}

		public Criteria andJcmnayosekanriCodGreaterThan(String value) {
			addCriterion("jcmnayosekanri_cod >", value, "jcmnayosekanriCod");
			return (Criteria) this;
		}

		public Criteria andJcmnayosekanriCodGreaterThanOrEqualTo(String value) {
			addCriterion("jcmnayosekanri_cod >=", value, "jcmnayosekanriCod");
			return (Criteria) this;
		}

		public Criteria andJcmnayosekanriCodLessThan(String value) {
			addCriterion("jcmnayosekanri_cod <", value, "jcmnayosekanriCod");
			return (Criteria) this;
		}

		public Criteria andJcmnayosekanriCodLessThanOrEqualTo(String value) {
			addCriterion("jcmnayosekanri_cod <=", value, "jcmnayosekanriCod");
			return (Criteria) this;
		}

		public Criteria andJcmnayosekanriCodLike(String value) {
			addCriterion("jcmnayosekanri_cod like", value, "jcmnayosekanriCod");
			return (Criteria) this;
		}

		public Criteria andJcmnayosekanriCodNotLike(String value) {
			addCriterion("jcmnayosekanri_cod not like", value, "jcmnayosekanriCod");
			return (Criteria) this;
		}

		public Criteria andJcmnayosekanriCodIn(List<String> values) {
			addCriterion("jcmnayosekanri_cod in", values, "jcmnayosekanriCod");
			return (Criteria) this;
		}

		public Criteria andJcmnayosekanriCodNotIn(List<String> values) {
			addCriterion("jcmnayosekanri_cod not in", values, "jcmnayosekanriCod");
			return (Criteria) this;
		}

		public Criteria andJcmnayosekanriCodBetween(String value1, String value2) {
			addCriterion("jcmnayosekanri_cod between", value1, value2, "jcmnayosekanriCod");
			return (Criteria) this;
		}

		public Criteria andJcmnayosekanriCodNotBetween(String value1, String value2) {
			addCriterion("jcmnayosekanri_cod not between", value1, value2, "jcmnayosekanriCod");
			return (Criteria) this;
		}

		public Criteria andJcmbumonCodIsNull() {
			addCriterion("jcmbumon_cod is null");
			return (Criteria) this;
		}

		public Criteria andJcmbumonCodIsNotNull() {
			addCriterion("jcmbumon_cod is not null");
			return (Criteria) this;
		}

		public Criteria andJcmbumonCodEqualTo(String value) {
			addCriterion("jcmbumon_cod =", value, "jcmbumonCod");
			return (Criteria) this;
		}

		public Criteria andJcmbumonCodNotEqualTo(String value) {
			addCriterion("jcmbumon_cod <>", value, "jcmbumonCod");
			return (Criteria) this;
		}

		public Criteria andJcmbumonCodGreaterThan(String value) {
			addCriterion("jcmbumon_cod >", value, "jcmbumonCod");
			return (Criteria) this;
		}

		public Criteria andJcmbumonCodGreaterThanOrEqualTo(String value) {
			addCriterion("jcmbumon_cod >=", value, "jcmbumonCod");
			return (Criteria) this;
		}

		public Criteria andJcmbumonCodLessThan(String value) {
			addCriterion("jcmbumon_cod <", value, "jcmbumonCod");
			return (Criteria) this;
		}

		public Criteria andJcmbumonCodLessThanOrEqualTo(String value) {
			addCriterion("jcmbumon_cod <=", value, "jcmbumonCod");
			return (Criteria) this;
		}

		public Criteria andJcmbumonCodLike(String value) {
			addCriterion("jcmbumon_cod like", value, "jcmbumonCod");
			return (Criteria) this;
		}

		public Criteria andJcmbumonCodNotLike(String value) {
			addCriterion("jcmbumon_cod not like", value, "jcmbumonCod");
			return (Criteria) this;
		}

		public Criteria andJcmbumonCodIn(List<String> values) {
			addCriterion("jcmbumon_cod in", values, "jcmbumonCod");
			return (Criteria) this;
		}

		public Criteria andJcmbumonCodNotIn(List<String> values) {
			addCriterion("jcmbumon_cod not in", values, "jcmbumonCod");
			return (Criteria) this;
		}

		public Criteria andJcmbumonCodBetween(String value1, String value2) {
			addCriterion("jcmbumon_cod between", value1, value2, "jcmbumonCod");
			return (Criteria) this;
		}

		public Criteria andJcmbumonCodNotBetween(String value1, String value2) {
			addCriterion("jcmbumon_cod not between", value1, value2, "jcmbumonCod");
			return (Criteria) this;
		}

		public Criteria andJcmtekiyostrYmdIsNull() {
			addCriterion("jcmtekiyostr_ymd is null");
			return (Criteria) this;
		}

		public Criteria andJcmtekiyostrYmdIsNotNull() {
			addCriterion("jcmtekiyostr_ymd is not null");
			return (Criteria) this;
		}

		public Criteria andJcmtekiyostrYmdEqualTo(Date value) {
			addCriterionForJDBCDate("jcmtekiyostr_ymd =", value, "jcmtekiyostrYmd");
			return (Criteria) this;
		}

		public Criteria andJcmtekiyostrYmdNotEqualTo(Date value) {
			addCriterionForJDBCDate("jcmtekiyostr_ymd <>", value, "jcmtekiyostrYmd");
			return (Criteria) this;
		}

		public Criteria andJcmtekiyostrYmdGreaterThan(Date value) {
			addCriterionForJDBCDate("jcmtekiyostr_ymd >", value, "jcmtekiyostrYmd");
			return (Criteria) this;
		}

		public Criteria andJcmtekiyostrYmdGreaterThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("jcmtekiyostr_ymd >=", value, "jcmtekiyostrYmd");
			return (Criteria) this;
		}

		public Criteria andJcmtekiyostrYmdLessThan(Date value) {
			addCriterionForJDBCDate("jcmtekiyostr_ymd <", value, "jcmtekiyostrYmd");
			return (Criteria) this;
		}

		public Criteria andJcmtekiyostrYmdLessThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("jcmtekiyostr_ymd <=", value, "jcmtekiyostrYmd");
			return (Criteria) this;
		}

		public Criteria andJcmtekiyostrYmdIn(List<Date> values) {
			addCriterionForJDBCDate("jcmtekiyostr_ymd in", values, "jcmtekiyostrYmd");
			return (Criteria) this;
		}

		public Criteria andJcmtekiyostrYmdNotIn(List<Date> values) {
			addCriterionForJDBCDate("jcmtekiyostr_ymd not in", values, "jcmtekiyostrYmd");
			return (Criteria) this;
		}

		public Criteria andJcmtekiyostrYmdBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("jcmtekiyostr_ymd between", value1, value2, "jcmtekiyostrYmd");
			return (Criteria) this;
		}

		public Criteria andJcmtekiyostrYmdNotBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("jcmtekiyostr_ymd not between", value1, value2, "jcmtekiyostrYmd");
			return (Criteria) this;
		}

		public Criteria andJcmsaimukejoKbnIsNull() {
			addCriterion("jcmsaimukejo_kbn is null");
			return (Criteria) this;
		}

		public Criteria andJcmsaimukejoKbnIsNotNull() {
			addCriterion("jcmsaimukejo_kbn is not null");
			return (Criteria) this;
		}

		public Criteria andJcmsaimukejoKbnEqualTo(String value) {
			addCriterion("jcmsaimukejo_kbn =", value, "jcmsaimukejoKbn");
			return (Criteria) this;
		}

		public Criteria andJcmsaimukejoKbnNotEqualTo(String value) {
			addCriterion("jcmsaimukejo_kbn <>", value, "jcmsaimukejoKbn");
			return (Criteria) this;
		}

		public Criteria andJcmsaimukejoKbnGreaterThan(String value) {
			addCriterion("jcmsaimukejo_kbn >", value, "jcmsaimukejoKbn");
			return (Criteria) this;
		}

		public Criteria andJcmsaimukejoKbnGreaterThanOrEqualTo(String value) {
			addCriterion("jcmsaimukejo_kbn >=", value, "jcmsaimukejoKbn");
			return (Criteria) this;
		}

		public Criteria andJcmsaimukejoKbnLessThan(String value) {
			addCriterion("jcmsaimukejo_kbn <", value, "jcmsaimukejoKbn");
			return (Criteria) this;
		}

		public Criteria andJcmsaimukejoKbnLessThanOrEqualTo(String value) {
			addCriterion("jcmsaimukejo_kbn <=", value, "jcmsaimukejoKbn");
			return (Criteria) this;
		}

		public Criteria andJcmsaimukejoKbnLike(String value) {
			addCriterion("jcmsaimukejo_kbn like", value, "jcmsaimukejoKbn");
			return (Criteria) this;
		}

		public Criteria andJcmsaimukejoKbnNotLike(String value) {
			addCriterion("jcmsaimukejo_kbn not like", value, "jcmsaimukejoKbn");
			return (Criteria) this;
		}

		public Criteria andJcmsaimukejoKbnIn(List<String> values) {
			addCriterion("jcmsaimukejo_kbn in", values, "jcmsaimukejoKbn");
			return (Criteria) this;
		}

		public Criteria andJcmsaimukejoKbnNotIn(List<String> values) {
			addCriterion("jcmsaimukejo_kbn not in", values, "jcmsaimukejoKbn");
			return (Criteria) this;
		}

		public Criteria andJcmsaimukejoKbnBetween(String value1, String value2) {
			addCriterion("jcmsaimukejo_kbn between", value1, value2, "jcmsaimukejoKbn");
			return (Criteria) this;
		}

		public Criteria andJcmsaimukejoKbnNotBetween(String value1, String value2) {
			addCriterion("jcmsaimukejo_kbn not between", value1, value2, "jcmsaimukejoKbn");
			return (Criteria) this;
		}

		public Criteria andJcmtekiyoendYmdIsNull() {
			addCriterion("jcmtekiyoend_ymd is null");
			return (Criteria) this;
		}

		public Criteria andJcmtekiyoendYmdIsNotNull() {
			addCriterion("jcmtekiyoend_ymd is not null");
			return (Criteria) this;
		}

		public Criteria andJcmtekiyoendYmdEqualTo(Date value) {
			addCriterionForJDBCDate("jcmtekiyoend_ymd =", value, "jcmtekiyoendYmd");
			return (Criteria) this;
		}

		public Criteria andJcmtekiyoendYmdNotEqualTo(Date value) {
			addCriterionForJDBCDate("jcmtekiyoend_ymd <>", value, "jcmtekiyoendYmd");
			return (Criteria) this;
		}

		public Criteria andJcmtekiyoendYmdGreaterThan(Date value) {
			addCriterionForJDBCDate("jcmtekiyoend_ymd >", value, "jcmtekiyoendYmd");
			return (Criteria) this;
		}

		public Criteria andJcmtekiyoendYmdGreaterThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("jcmtekiyoend_ymd >=", value, "jcmtekiyoendYmd");
			return (Criteria) this;
		}

		public Criteria andJcmtekiyoendYmdLessThan(Date value) {
			addCriterionForJDBCDate("jcmtekiyoend_ymd <", value, "jcmtekiyoendYmd");
			return (Criteria) this;
		}

		public Criteria andJcmtekiyoendYmdLessThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("jcmtekiyoend_ymd <=", value, "jcmtekiyoendYmd");
			return (Criteria) this;
		}

		public Criteria andJcmtekiyoendYmdIn(List<Date> values) {
			addCriterionForJDBCDate("jcmtekiyoend_ymd in", values, "jcmtekiyoendYmd");
			return (Criteria) this;
		}

		public Criteria andJcmtekiyoendYmdNotIn(List<Date> values) {
			addCriterionForJDBCDate("jcmtekiyoend_ymd not in", values, "jcmtekiyoendYmd");
			return (Criteria) this;
		}

		public Criteria andJcmtekiyoendYmdBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("jcmtekiyoend_ymd between", value1, value2, "jcmtekiyoendYmd");
			return (Criteria) this;
		}

		public Criteria andJcmtekiyoendYmdNotBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("jcmtekiyoend_ymd not between", value1, value2, "jcmtekiyoendYmd");
			return (Criteria) this;
		}

		public Criteria andJcmcrtYmdIsNull() {
			addCriterion("jcmcrt_ymd is null");
			return (Criteria) this;
		}

		public Criteria andJcmcrtYmdIsNotNull() {
			addCriterion("jcmcrt_ymd is not null");
			return (Criteria) this;
		}

		public Criteria andJcmcrtYmdEqualTo(Date value) {
			addCriterionForJDBCDate("jcmcrt_ymd =", value, "jcmcrtYmd");
			return (Criteria) this;
		}

		public Criteria andJcmcrtYmdNotEqualTo(Date value) {
			addCriterionForJDBCDate("jcmcrt_ymd <>", value, "jcmcrtYmd");
			return (Criteria) this;
		}

		public Criteria andJcmcrtYmdGreaterThan(Date value) {
			addCriterionForJDBCDate("jcmcrt_ymd >", value, "jcmcrtYmd");
			return (Criteria) this;
		}

		public Criteria andJcmcrtYmdGreaterThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("jcmcrt_ymd >=", value, "jcmcrtYmd");
			return (Criteria) this;
		}

		public Criteria andJcmcrtYmdLessThan(Date value) {
			addCriterionForJDBCDate("jcmcrt_ymd <", value, "jcmcrtYmd");
			return (Criteria) this;
		}

		public Criteria andJcmcrtYmdLessThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("jcmcrt_ymd <=", value, "jcmcrtYmd");
			return (Criteria) this;
		}

		public Criteria andJcmcrtYmdIn(List<Date> values) {
			addCriterionForJDBCDate("jcmcrt_ymd in", values, "jcmcrtYmd");
			return (Criteria) this;
		}

		public Criteria andJcmcrtYmdNotIn(List<Date> values) {
			addCriterionForJDBCDate("jcmcrt_ymd not in", values, "jcmcrtYmd");
			return (Criteria) this;
		}

		public Criteria andJcmcrtYmdBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("jcmcrt_ymd between", value1, value2, "jcmcrtYmd");
			return (Criteria) this;
		}

		public Criteria andJcmcrtYmdNotBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("jcmcrt_ymd not between", value1, value2, "jcmcrtYmd");
			return (Criteria) this;
		}

		public Criteria andJcmcrtshainCodIsNull() {
			addCriterion("jcmcrtshain_cod is null");
			return (Criteria) this;
		}

		public Criteria andJcmcrtshainCodIsNotNull() {
			addCriterion("jcmcrtshain_cod is not null");
			return (Criteria) this;
		}

		public Criteria andJcmcrtshainCodEqualTo(String value) {
			addCriterion("jcmcrtshain_cod =", value, "jcmcrtshainCod");
			return (Criteria) this;
		}

		public Criteria andJcmcrtshainCodNotEqualTo(String value) {
			addCriterion("jcmcrtshain_cod <>", value, "jcmcrtshainCod");
			return (Criteria) this;
		}

		public Criteria andJcmcrtshainCodGreaterThan(String value) {
			addCriterion("jcmcrtshain_cod >", value, "jcmcrtshainCod");
			return (Criteria) this;
		}

		public Criteria andJcmcrtshainCodGreaterThanOrEqualTo(String value) {
			addCriterion("jcmcrtshain_cod >=", value, "jcmcrtshainCod");
			return (Criteria) this;
		}

		public Criteria andJcmcrtshainCodLessThan(String value) {
			addCriterion("jcmcrtshain_cod <", value, "jcmcrtshainCod");
			return (Criteria) this;
		}

		public Criteria andJcmcrtshainCodLessThanOrEqualTo(String value) {
			addCriterion("jcmcrtshain_cod <=", value, "jcmcrtshainCod");
			return (Criteria) this;
		}

		public Criteria andJcmcrtshainCodLike(String value) {
			addCriterion("jcmcrtshain_cod like", value, "jcmcrtshainCod");
			return (Criteria) this;
		}

		public Criteria andJcmcrtshainCodNotLike(String value) {
			addCriterion("jcmcrtshain_cod not like", value, "jcmcrtshainCod");
			return (Criteria) this;
		}

		public Criteria andJcmcrtshainCodIn(List<String> values) {
			addCriterion("jcmcrtshain_cod in", values, "jcmcrtshainCod");
			return (Criteria) this;
		}

		public Criteria andJcmcrtshainCodNotIn(List<String> values) {
			addCriterion("jcmcrtshain_cod not in", values, "jcmcrtshainCod");
			return (Criteria) this;
		}

		public Criteria andJcmcrtshainCodBetween(String value1, String value2) {
			addCriterion("jcmcrtshain_cod between", value1, value2, "jcmcrtshainCod");
			return (Criteria) this;
		}

		public Criteria andJcmcrtshainCodNotBetween(String value1, String value2) {
			addCriterion("jcmcrtshain_cod not between", value1, value2, "jcmcrtshainCod");
			return (Criteria) this;
		}

		public Criteria andJcmupdYmdIsNull() {
			addCriterion("jcmupd_ymd is null");
			return (Criteria) this;
		}

		public Criteria andJcmupdYmdIsNotNull() {
			addCriterion("jcmupd_ymd is not null");
			return (Criteria) this;
		}

		public Criteria andJcmupdYmdEqualTo(Date value) {
			addCriterionForJDBCDate("jcmupd_ymd =", value, "jcmupdYmd");
			return (Criteria) this;
		}

		public Criteria andJcmupdYmdNotEqualTo(Date value) {
			addCriterionForJDBCDate("jcmupd_ymd <>", value, "jcmupdYmd");
			return (Criteria) this;
		}

		public Criteria andJcmupdYmdGreaterThan(Date value) {
			addCriterionForJDBCDate("jcmupd_ymd >", value, "jcmupdYmd");
			return (Criteria) this;
		}

		public Criteria andJcmupdYmdGreaterThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("jcmupd_ymd >=", value, "jcmupdYmd");
			return (Criteria) this;
		}

		public Criteria andJcmupdYmdLessThan(Date value) {
			addCriterionForJDBCDate("jcmupd_ymd <", value, "jcmupdYmd");
			return (Criteria) this;
		}

		public Criteria andJcmupdYmdLessThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("jcmupd_ymd <=", value, "jcmupdYmd");
			return (Criteria) this;
		}

		public Criteria andJcmupdYmdIn(List<Date> values) {
			addCriterionForJDBCDate("jcmupd_ymd in", values, "jcmupdYmd");
			return (Criteria) this;
		}

		public Criteria andJcmupdYmdNotIn(List<Date> values) {
			addCriterionForJDBCDate("jcmupd_ymd not in", values, "jcmupdYmd");
			return (Criteria) this;
		}

		public Criteria andJcmupdYmdBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("jcmupd_ymd between", value1, value2, "jcmupdYmd");
			return (Criteria) this;
		}

		public Criteria andJcmupdYmdNotBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("jcmupd_ymd not between", value1, value2, "jcmupdYmd");
			return (Criteria) this;
		}

		public Criteria andJcmupdshainCodIsNull() {
			addCriterion("jcmupdshain_cod is null");
			return (Criteria) this;
		}

		public Criteria andJcmupdshainCodIsNotNull() {
			addCriterion("jcmupdshain_cod is not null");
			return (Criteria) this;
		}

		public Criteria andJcmupdshainCodEqualTo(String value) {
			addCriterion("jcmupdshain_cod =", value, "jcmupdshainCod");
			return (Criteria) this;
		}

		public Criteria andJcmupdshainCodNotEqualTo(String value) {
			addCriterion("jcmupdshain_cod <>", value, "jcmupdshainCod");
			return (Criteria) this;
		}

		public Criteria andJcmupdshainCodGreaterThan(String value) {
			addCriterion("jcmupdshain_cod >", value, "jcmupdshainCod");
			return (Criteria) this;
		}

		public Criteria andJcmupdshainCodGreaterThanOrEqualTo(String value) {
			addCriterion("jcmupdshain_cod >=", value, "jcmupdshainCod");
			return (Criteria) this;
		}

		public Criteria andJcmupdshainCodLessThan(String value) {
			addCriterion("jcmupdshain_cod <", value, "jcmupdshainCod");
			return (Criteria) this;
		}

		public Criteria andJcmupdshainCodLessThanOrEqualTo(String value) {
			addCriterion("jcmupdshain_cod <=", value, "jcmupdshainCod");
			return (Criteria) this;
		}

		public Criteria andJcmupdshainCodLike(String value) {
			addCriterion("jcmupdshain_cod like", value, "jcmupdshainCod");
			return (Criteria) this;
		}

		public Criteria andJcmupdshainCodNotLike(String value) {
			addCriterion("jcmupdshain_cod not like", value, "jcmupdshainCod");
			return (Criteria) this;
		}

		public Criteria andJcmupdshainCodIn(List<String> values) {
			addCriterion("jcmupdshain_cod in", values, "jcmupdshainCod");
			return (Criteria) this;
		}

		public Criteria andJcmupdshainCodNotIn(List<String> values) {
			addCriterion("jcmupdshain_cod not in", values, "jcmupdshainCod");
			return (Criteria) this;
		}

		public Criteria andJcmupdshainCodBetween(String value1, String value2) {
			addCriterion("jcmupdshain_cod between", value1, value2, "jcmupdshainCod");
			return (Criteria) this;
		}

		public Criteria andJcmupdshainCodNotBetween(String value1, String value2) {
			addCriterion("jcmupdshain_cod not between", value1, value2, "jcmupdshainCod");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table tmmbumonnayosemi
	 * @mbg.generated  Fri Nov 11 16:38:00 JST 2022
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}
	
    private Integer limit;

    public void setLimit(Integer limit) {
        this.limit = limit;
    }

    public Integer getLimit() {
        return limit;
    }

    /**
	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tmmbumonnayosemi
     *
     * @mbg.generated do_not_delete_during_merge Sun Nov 13 06:28:17 JST 2022
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }
}