package com.wetech.ryutsumodel.model.entity;

import java.util.Date;

public class Tmtmsoshiki extends TmtmsoshikiKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tmtmsoshiki.comsosk1_cod
     *
     * @mbg.generated Thu Sep 15 17:29:11 JST 2022
     */
    private String comsosk1_cod;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tmtmsoshiki.comsosknm11_knj
     *
     * @mbg.generated Thu Sep 15 17:29:11 JST 2022
     */
    private String comsosknm11_knj;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tmtmsoshiki.comsosknm21_knj
     *
     * @mbg.generated Thu Sep 15 17:29:11 JST 2022
     */
    private String comsosknm21_knj;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tmtmsoshiki.comsosknm11_kna
     *
     * @mbg.generated Thu Sep 15 17:29:11 JST 2022
     */
    private String comsosknm11_kna;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tmtmsoshiki.comsosknm21_kna
     *
     * @mbg.generated Thu Sep 15 17:29:11 JST 2022
     */
    private String comsosknm21_kna;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tmtmsoshiki.comhyojijun1_num
     *
     * @mbg.generated Thu Sep 15 17:29:11 JST 2022
     */
    private Integer comhyojijun1_num;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tmtmsoshiki.comsosk2_cod
     *
     * @mbg.generated Thu Sep 15 17:29:11 JST 2022
     */
    private String comsosk2_cod;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tmtmsoshiki.comsosknm12_knj
     *
     * @mbg.generated Thu Sep 15 17:29:11 JST 2022
     */
    private String comsosknm12_knj;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tmtmsoshiki.comsosknm22_knj
     *
     * @mbg.generated Thu Sep 15 17:29:11 JST 2022
     */
    private String comsosknm22_knj;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tmtmsoshiki.comsosknm12_kna
     *
     * @mbg.generated Thu Sep 15 17:29:11 JST 2022
     */
    private String comsosknm12_kna;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tmtmsoshiki.comsosknm22_kna
     *
     * @mbg.generated Thu Sep 15 17:29:11 JST 2022
     */
    private String comsosknm22_kna;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tmtmsoshiki.comhyojijun2_num
     *
     * @mbg.generated Thu Sep 15 17:29:11 JST 2022
     */
    private Integer comhyojijun2_num;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tmtmsoshiki.comsosk3_cod
     *
     * @mbg.generated Thu Sep 15 17:29:11 JST 2022
     */
    private String comsosk3_cod;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tmtmsoshiki.comsosknm13_knj
     *
     * @mbg.generated Thu Sep 15 17:29:11 JST 2022
     */
    private String comsosknm13_knj;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tmtmsoshiki.comsosknm23_knj
     *
     * @mbg.generated Thu Sep 15 17:29:11 JST 2022
     */
    private String comsosknm23_knj;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tmtmsoshiki.comsosknm13_kna
     *
     * @mbg.generated Thu Sep 15 17:29:11 JST 2022
     */
    private String comsosknm13_kna;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tmtmsoshiki.comsosknm23_kna
     *
     * @mbg.generated Thu Sep 15 17:29:11 JST 2022
     */
    private String comsosknm23_kna;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tmtmsoshiki.comhyojijun3_num
     *
     * @mbg.generated Thu Sep 15 17:29:11 JST 2022
     */
    private Integer comhyojijun3_num;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tmtmsoshiki.comsosk4_cod
     *
     * @mbg.generated Thu Sep 15 17:29:11 JST 2022
     */
    private String comsosk4_cod;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tmtmsoshiki.comsosknm14_knj
     *
     * @mbg.generated Thu Sep 15 17:29:11 JST 2022
     */
    private String comsosknm14_knj;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tmtmsoshiki.comsosknm24_knj
     *
     * @mbg.generated Thu Sep 15 17:29:11 JST 2022
     */
    private String comsosknm24_knj;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tmtmsoshiki.comsosknm14_kna
     *
     * @mbg.generated Thu Sep 15 17:29:11 JST 2022
     */
    private String comsosknm14_kna;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tmtmsoshiki.comsosknm24_kna
     *
     * @mbg.generated Thu Sep 15 17:29:11 JST 2022
     */
    private String comsosknm24_kna;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tmtmsoshiki.comhyojijun4_num
     *
     * @mbg.generated Thu Sep 15 17:29:11 JST 2022
     */
    private Integer comhyojijun4_num;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tmtmsoshiki.comsosk5_cod
     *
     * @mbg.generated Thu Sep 15 17:29:11 JST 2022
     */
    private String comsosk5_cod;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tmtmsoshiki.comsosknm15_knj
     *
     * @mbg.generated Thu Sep 15 17:29:11 JST 2022
     */
    private String comsosknm15_knj;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tmtmsoshiki.comsosknm25_knj
     *
     * @mbg.generated Thu Sep 15 17:29:11 JST 2022
     */
    private String comsosknm25_knj;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tmtmsoshiki.comsosknm15_kna
     *
     * @mbg.generated Thu Sep 15 17:29:11 JST 2022
     */
    private String comsosknm15_kna;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tmtmsoshiki.comsosknm25_kna
     *
     * @mbg.generated Thu Sep 15 17:29:11 JST 2022
     */
    private String comsosknm25_kna;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tmtmsoshiki.comhyojijun5_num
     *
     * @mbg.generated Thu Sep 15 17:29:11 JST 2022
     */
    private Integer comhyojijun5_num;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tmtmsoshiki.comsosk6_cod
     *
     * @mbg.generated Thu Sep 15 17:29:11 JST 2022
     */
    private String comsosk6_cod;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tmtmsoshiki.comsosknm16_knj
     *
     * @mbg.generated Thu Sep 15 17:29:11 JST 2022
     */
    private String comsosknm16_knj;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tmtmsoshiki.comsosknm26_knj
     *
     * @mbg.generated Thu Sep 15 17:29:11 JST 2022
     */
    private String comsosknm26_knj;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tmtmsoshiki.comsosknm16_kna
     *
     * @mbg.generated Thu Sep 15 17:29:11 JST 2022
     */
    private String comsosknm16_kna;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tmtmsoshiki.comsosknm26_kna
     *
     * @mbg.generated Thu Sep 15 17:29:11 JST 2022
     */
    private String comsosknm26_kna;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tmtmsoshiki.comhyojijun6_num
     *
     * @mbg.generated Thu Sep 15 17:29:11 JST 2022
     */
    private Integer comhyojijun6_num;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tmtmsoshiki.comsosk7_cod
     *
     * @mbg.generated Thu Sep 15 17:29:11 JST 2022
     */
    private String comsosk7_cod;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tmtmsoshiki.comsosknm17_knj
     *
     * @mbg.generated Thu Sep 15 17:29:11 JST 2022
     */
    private String comsosknm17_knj;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tmtmsoshiki.comsosknm27_knj
     *
     * @mbg.generated Thu Sep 15 17:29:11 JST 2022
     */
    private String comsosknm27_knj;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tmtmsoshiki.comsosknm17_kna
     *
     * @mbg.generated Thu Sep 15 17:29:11 JST 2022
     */
    private String comsosknm17_kna;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tmtmsoshiki.comsosknm27_kna
     *
     * @mbg.generated Thu Sep 15 17:29:11 JST 2022
     */
    private String comsosknm27_kna;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tmtmsoshiki.comhyojijun7_num
     *
     * @mbg.generated Thu Sep 15 17:29:11 JST 2022
     */
    private Integer comhyojijun7_num;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tmtmsoshiki.comsosk8_cod
     *
     * @mbg.generated Thu Sep 15 17:29:11 JST 2022
     */
    private String comsosk8_cod;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tmtmsoshiki.comsosknm18_knj
     *
     * @mbg.generated Thu Sep 15 17:29:11 JST 2022
     */
    private String comsosknm18_knj;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tmtmsoshiki.comsosknm28_knj
     *
     * @mbg.generated Thu Sep 15 17:29:11 JST 2022
     */
    private String comsosknm28_knj;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tmtmsoshiki.comsosknm18_kna
     *
     * @mbg.generated Thu Sep 15 17:29:11 JST 2022
     */
    private String comsosknm18_kna;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tmtmsoshiki.comsosknm28_kna
     *
     * @mbg.generated Thu Sep 15 17:29:11 JST 2022
     */
    private String comsosknm28_kna;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tmtmsoshiki.comhyojijun8_num
     *
     * @mbg.generated Thu Sep 15 17:29:11 JST 2022
     */
    private Integer comhyojijun8_num;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tmtmsoshiki.comsosk9_cod
     *
     * @mbg.generated Thu Sep 15 17:29:11 JST 2022
     */
    private String comsosk9_cod;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tmtmsoshiki.comsosknm19_knj
     *
     * @mbg.generated Thu Sep 15 17:29:11 JST 2022
     */
    private String comsosknm19_knj;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tmtmsoshiki.comsosknm29_knj
     *
     * @mbg.generated Thu Sep 15 17:29:11 JST 2022
     */
    private String comsosknm29_knj;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tmtmsoshiki.comsosknm19_kna
     *
     * @mbg.generated Thu Sep 15 17:29:11 JST 2022
     */
    private String comsosknm19_kna;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tmtmsoshiki.comsosknm29_kna
     *
     * @mbg.generated Thu Sep 15 17:29:11 JST 2022
     */
    private String comsosknm29_kna;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tmtmsoshiki.comhyojijun9_num
     *
     * @mbg.generated Thu Sep 15 17:29:11 JST 2022
     */
    private Integer comhyojijun9_num;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tmtmsoshiki.comsosk10_cod
     *
     * @mbg.generated Thu Sep 15 17:29:11 JST 2022
     */
    private String comsosk10_cod;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tmtmsoshiki.comsosknm110_knj
     *
     * @mbg.generated Thu Sep 15 17:29:11 JST 2022
     */
    private String comsosknm110_knj;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tmtmsoshiki.comsosknm210_knj
     *
     * @mbg.generated Thu Sep 15 17:29:11 JST 2022
     */
    private String comsosknm210_knj;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tmtmsoshiki.comsosknm110_kna
     *
     * @mbg.generated Thu Sep 15 17:29:11 JST 2022
     */
    private String comsosknm110_kna;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tmtmsoshiki.comsosknm210_kna
     *
     * @mbg.generated Thu Sep 15 17:29:11 JST 2022
     */
    private String comsosknm210_kna;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tmtmsoshiki.comhyojijun10_num
     *
     * @mbg.generated Thu Sep 15 17:29:11 JST 2022
     */
    private Integer comhyojijun10_num;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tmtmsoshiki.comyobi_kbn
     *
     * @mbg.generated Thu Sep 15 17:29:11 JST 2022
     */
    private String comyobi_kbn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tmtmsoshiki.comtekiyoend_ymd
     *
     * @mbg.generated Thu Sep 15 17:29:11 JST 2022
     */
    private Date comtekiyoend_ymd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tmtmsoshiki.comcrt_ymd
     *
     * @mbg.generated Thu Sep 15 17:29:11 JST 2022
     */
    private Date comcrt_ymd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tmtmsoshiki.comcrtshain_cod
     *
     * @mbg.generated Thu Sep 15 17:29:11 JST 2022
     */
    private String comcrtshain_cod;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tmtmsoshiki.comupd_ymd
     *
     * @mbg.generated Thu Sep 15 17:29:11 JST 2022
     */
    private Date comupd_ymd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tmtmsoshiki.comupdshain_cod
     *
     * @mbg.generated Thu Sep 15 17:29:11 JST 2022
     */
    private String comupdshain_cod;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tmtmsoshiki.comsosk1_cod
     *
     * @return the value of tmtmsoshiki.comsosk1_cod
     *
     * @mbg.generated Thu Sep 15 17:29:11 JST 2022
     */
    public String getComsosk1_cod() {
        return comsosk1_cod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tmtmsoshiki.comsosk1_cod
     *
     * @param comsosk1_cod the value for tmtmsoshiki.comsosk1_cod
     *
     * @mbg.generated Thu Sep 15 17:29:11 JST 2022
     */
    public void setComsosk1_cod(String comsosk1_cod) {
        this.comsosk1_cod = comsosk1_cod == null ? null : comsosk1_cod.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tmtmsoshiki.comsosknm11_knj
     *
     * @return the value of tmtmsoshiki.comsosknm11_knj
     *
     * @mbg.generated Thu Sep 15 17:29:11 JST 2022
     */
    public String getComsosknm11_knj() {
        return comsosknm11_knj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tmtmsoshiki.comsosknm11_knj
     *
     * @param comsosknm11_knj the value for tmtmsoshiki.comsosknm11_knj
     *
     * @mbg.generated Thu Sep 15 17:29:11 JST 2022
     */
    public void setComsosknm11_knj(String comsosknm11_knj) {
        this.comsosknm11_knj = comsosknm11_knj == null ? null : comsosknm11_knj.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tmtmsoshiki.comsosknm21_knj
     *
     * @return the value of tmtmsoshiki.comsosknm21_knj
     *
     * @mbg.generated Thu Sep 15 17:29:11 JST 2022
     */
    public String getComsosknm21_knj() {
        return comsosknm21_knj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tmtmsoshiki.comsosknm21_knj
     *
     * @param comsosknm21_knj the value for tmtmsoshiki.comsosknm21_knj
     *
     * @mbg.generated Thu Sep 15 17:29:11 JST 2022
     */
    public void setComsosknm21_knj(String comsosknm21_knj) {
        this.comsosknm21_knj = comsosknm21_knj == null ? null : comsosknm21_knj.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tmtmsoshiki.comsosknm11_kna
     *
     * @return the value of tmtmsoshiki.comsosknm11_kna
     *
     * @mbg.generated Thu Sep 15 17:29:11 JST 2022
     */
    public String getComsosknm11_kna() {
        return comsosknm11_kna;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tmtmsoshiki.comsosknm11_kna
     *
     * @param comsosknm11_kna the value for tmtmsoshiki.comsosknm11_kna
     *
     * @mbg.generated Thu Sep 15 17:29:11 JST 2022
     */
    public void setComsosknm11_kna(String comsosknm11_kna) {
        this.comsosknm11_kna = comsosknm11_kna == null ? null : comsosknm11_kna.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tmtmsoshiki.comsosknm21_kna
     *
     * @return the value of tmtmsoshiki.comsosknm21_kna
     *
     * @mbg.generated Thu Sep 15 17:29:11 JST 2022
     */
    public String getComsosknm21_kna() {
        return comsosknm21_kna;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tmtmsoshiki.comsosknm21_kna
     *
     * @param comsosknm21_kna the value for tmtmsoshiki.comsosknm21_kna
     *
     * @mbg.generated Thu Sep 15 17:29:11 JST 2022
     */
    public void setComsosknm21_kna(String comsosknm21_kna) {
        this.comsosknm21_kna = comsosknm21_kna == null ? null : comsosknm21_kna.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tmtmsoshiki.comhyojijun1_num
     *
     * @return the value of tmtmsoshiki.comhyojijun1_num
     *
     * @mbg.generated Thu Sep 15 17:29:11 JST 2022
     */
    public Integer getComhyojijun1_num() {
        return comhyojijun1_num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tmtmsoshiki.comhyojijun1_num
     *
     * @param comhyojijun1_num the value for tmtmsoshiki.comhyojijun1_num
     *
     * @mbg.generated Thu Sep 15 17:29:11 JST 2022
     */
    public void setComhyojijun1_num(Integer comhyojijun1_num) {
        this.comhyojijun1_num = comhyojijun1_num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tmtmsoshiki.comsosk2_cod
     *
     * @return the value of tmtmsoshiki.comsosk2_cod
     *
     * @mbg.generated Thu Sep 15 17:29:11 JST 2022
     */
    public String getComsosk2_cod() {
        return comsosk2_cod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tmtmsoshiki.comsosk2_cod
     *
     * @param comsosk2_cod the value for tmtmsoshiki.comsosk2_cod
     *
     * @mbg.generated Thu Sep 15 17:29:11 JST 2022
     */
    public void setComsosk2_cod(String comsosk2_cod) {
        this.comsosk2_cod = comsosk2_cod == null ? null : comsosk2_cod.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tmtmsoshiki.comsosknm12_knj
     *
     * @return the value of tmtmsoshiki.comsosknm12_knj
     *
     * @mbg.generated Thu Sep 15 17:29:11 JST 2022
     */
    public String getComsosknm12_knj() {
        return comsosknm12_knj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tmtmsoshiki.comsosknm12_knj
     *
     * @param comsosknm12_knj the value for tmtmsoshiki.comsosknm12_knj
     *
     * @mbg.generated Thu Sep 15 17:29:11 JST 2022
     */
    public void setComsosknm12_knj(String comsosknm12_knj) {
        this.comsosknm12_knj = comsosknm12_knj == null ? null : comsosknm12_knj.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tmtmsoshiki.comsosknm22_knj
     *
     * @return the value of tmtmsoshiki.comsosknm22_knj
     *
     * @mbg.generated Thu Sep 15 17:29:11 JST 2022
     */
    public String getComsosknm22_knj() {
        return comsosknm22_knj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tmtmsoshiki.comsosknm22_knj
     *
     * @param comsosknm22_knj the value for tmtmsoshiki.comsosknm22_knj
     *
     * @mbg.generated Thu Sep 15 17:29:11 JST 2022
     */
    public void setComsosknm22_knj(String comsosknm22_knj) {
        this.comsosknm22_knj = comsosknm22_knj == null ? null : comsosknm22_knj.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tmtmsoshiki.comsosknm12_kna
     *
     * @return the value of tmtmsoshiki.comsosknm12_kna
     *
     * @mbg.generated Thu Sep 15 17:29:11 JST 2022
     */
    public String getComsosknm12_kna() {
        return comsosknm12_kna;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tmtmsoshiki.comsosknm12_kna
     *
     * @param comsosknm12_kna the value for tmtmsoshiki.comsosknm12_kna
     *
     * @mbg.generated Thu Sep 15 17:29:11 JST 2022
     */
    public void setComsosknm12_kna(String comsosknm12_kna) {
        this.comsosknm12_kna = comsosknm12_kna == null ? null : comsosknm12_kna.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tmtmsoshiki.comsosknm22_kna
     *
     * @return the value of tmtmsoshiki.comsosknm22_kna
     *
     * @mbg.generated Thu Sep 15 17:29:11 JST 2022
     */
    public String getComsosknm22_kna() {
        return comsosknm22_kna;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tmtmsoshiki.comsosknm22_kna
     *
     * @param comsosknm22_kna the value for tmtmsoshiki.comsosknm22_kna
     *
     * @mbg.generated Thu Sep 15 17:29:11 JST 2022
     */
    public void setComsosknm22_kna(String comsosknm22_kna) {
        this.comsosknm22_kna = comsosknm22_kna == null ? null : comsosknm22_kna.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tmtmsoshiki.comhyojijun2_num
     *
     * @return the value of tmtmsoshiki.comhyojijun2_num
     *
     * @mbg.generated Thu Sep 15 17:29:11 JST 2022
     */
    public Integer getComhyojijun2_num() {
        return comhyojijun2_num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tmtmsoshiki.comhyojijun2_num
     *
     * @param comhyojijun2_num the value for tmtmsoshiki.comhyojijun2_num
     *
     * @mbg.generated Thu Sep 15 17:29:11 JST 2022
     */
    public void setComhyojijun2_num(Integer comhyojijun2_num) {
        this.comhyojijun2_num = comhyojijun2_num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tmtmsoshiki.comsosk3_cod
     *
     * @return the value of tmtmsoshiki.comsosk3_cod
     *
     * @mbg.generated Thu Sep 15 17:29:11 JST 2022
     */
    public String getComsosk3_cod() {
        return comsosk3_cod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tmtmsoshiki.comsosk3_cod
     *
     * @param comsosk3_cod the value for tmtmsoshiki.comsosk3_cod
     *
     * @mbg.generated Thu Sep 15 17:29:11 JST 2022
     */
    public void setComsosk3_cod(String comsosk3_cod) {
        this.comsosk3_cod = comsosk3_cod == null ? null : comsosk3_cod.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tmtmsoshiki.comsosknm13_knj
     *
     * @return the value of tmtmsoshiki.comsosknm13_knj
     *
     * @mbg.generated Thu Sep 15 17:29:11 JST 2022
     */
    public String getComsosknm13_knj() {
        return comsosknm13_knj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tmtmsoshiki.comsosknm13_knj
     *
     * @param comsosknm13_knj the value for tmtmsoshiki.comsosknm13_knj
     *
     * @mbg.generated Thu Sep 15 17:29:11 JST 2022
     */
    public void setComsosknm13_knj(String comsosknm13_knj) {
        this.comsosknm13_knj = comsosknm13_knj == null ? null : comsosknm13_knj.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tmtmsoshiki.comsosknm23_knj
     *
     * @return the value of tmtmsoshiki.comsosknm23_knj
     *
     * @mbg.generated Thu Sep 15 17:29:11 JST 2022
     */
    public String getComsosknm23_knj() {
        return comsosknm23_knj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tmtmsoshiki.comsosknm23_knj
     *
     * @param comsosknm23_knj the value for tmtmsoshiki.comsosknm23_knj
     *
     * @mbg.generated Thu Sep 15 17:29:11 JST 2022
     */
    public void setComsosknm23_knj(String comsosknm23_knj) {
        this.comsosknm23_knj = comsosknm23_knj == null ? null : comsosknm23_knj.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tmtmsoshiki.comsosknm13_kna
     *
     * @return the value of tmtmsoshiki.comsosknm13_kna
     *
     * @mbg.generated Thu Sep 15 17:29:11 JST 2022
     */
    public String getComsosknm13_kna() {
        return comsosknm13_kna;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tmtmsoshiki.comsosknm13_kna
     *
     * @param comsosknm13_kna the value for tmtmsoshiki.comsosknm13_kna
     *
     * @mbg.generated Thu Sep 15 17:29:11 JST 2022
     */
    public void setComsosknm13_kna(String comsosknm13_kna) {
        this.comsosknm13_kna = comsosknm13_kna == null ? null : comsosknm13_kna.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tmtmsoshiki.comsosknm23_kna
     *
     * @return the value of tmtmsoshiki.comsosknm23_kna
     *
     * @mbg.generated Thu Sep 15 17:29:11 JST 2022
     */
    public String getComsosknm23_kna() {
        return comsosknm23_kna;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tmtmsoshiki.comsosknm23_kna
     *
     * @param comsosknm23_kna the value for tmtmsoshiki.comsosknm23_kna
     *
     * @mbg.generated Thu Sep 15 17:29:11 JST 2022
     */
    public void setComsosknm23_kna(String comsosknm23_kna) {
        this.comsosknm23_kna = comsosknm23_kna == null ? null : comsosknm23_kna.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tmtmsoshiki.comhyojijun3_num
     *
     * @return the value of tmtmsoshiki.comhyojijun3_num
     *
     * @mbg.generated Thu Sep 15 17:29:11 JST 2022
     */
    public Integer getComhyojijun3_num() {
        return comhyojijun3_num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tmtmsoshiki.comhyojijun3_num
     *
     * @param comhyojijun3_num the value for tmtmsoshiki.comhyojijun3_num
     *
     * @mbg.generated Thu Sep 15 17:29:11 JST 2022
     */
    public void setComhyojijun3_num(Integer comhyojijun3_num) {
        this.comhyojijun3_num = comhyojijun3_num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tmtmsoshiki.comsosk4_cod
     *
     * @return the value of tmtmsoshiki.comsosk4_cod
     *
     * @mbg.generated Thu Sep 15 17:29:11 JST 2022
     */
    public String getComsosk4_cod() {
        return comsosk4_cod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tmtmsoshiki.comsosk4_cod
     *
     * @param comsosk4_cod the value for tmtmsoshiki.comsosk4_cod
     *
     * @mbg.generated Thu Sep 15 17:29:11 JST 2022
     */
    public void setComsosk4_cod(String comsosk4_cod) {
        this.comsosk4_cod = comsosk4_cod == null ? null : comsosk4_cod.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tmtmsoshiki.comsosknm14_knj
     *
     * @return the value of tmtmsoshiki.comsosknm14_knj
     *
     * @mbg.generated Thu Sep 15 17:29:11 JST 2022
     */
    public String getComsosknm14_knj() {
        return comsosknm14_knj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tmtmsoshiki.comsosknm14_knj
     *
     * @param comsosknm14_knj the value for tmtmsoshiki.comsosknm14_knj
     *
     * @mbg.generated Thu Sep 15 17:29:11 JST 2022
     */
    public void setComsosknm14_knj(String comsosknm14_knj) {
        this.comsosknm14_knj = comsosknm14_knj == null ? null : comsosknm14_knj.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tmtmsoshiki.comsosknm24_knj
     *
     * @return the value of tmtmsoshiki.comsosknm24_knj
     *
     * @mbg.generated Thu Sep 15 17:29:11 JST 2022
     */
    public String getComsosknm24_knj() {
        return comsosknm24_knj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tmtmsoshiki.comsosknm24_knj
     *
     * @param comsosknm24_knj the value for tmtmsoshiki.comsosknm24_knj
     *
     * @mbg.generated Thu Sep 15 17:29:11 JST 2022
     */
    public void setComsosknm24_knj(String comsosknm24_knj) {
        this.comsosknm24_knj = comsosknm24_knj == null ? null : comsosknm24_knj.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tmtmsoshiki.comsosknm14_kna
     *
     * @return the value of tmtmsoshiki.comsosknm14_kna
     *
     * @mbg.generated Thu Sep 15 17:29:11 JST 2022
     */
    public String getComsosknm14_kna() {
        return comsosknm14_kna;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tmtmsoshiki.comsosknm14_kna
     *
     * @param comsosknm14_kna the value for tmtmsoshiki.comsosknm14_kna
     *
     * @mbg.generated Thu Sep 15 17:29:11 JST 2022
     */
    public void setComsosknm14_kna(String comsosknm14_kna) {
        this.comsosknm14_kna = comsosknm14_kna == null ? null : comsosknm14_kna.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tmtmsoshiki.comsosknm24_kna
     *
     * @return the value of tmtmsoshiki.comsosknm24_kna
     *
     * @mbg.generated Thu Sep 15 17:29:11 JST 2022
     */
    public String getComsosknm24_kna() {
        return comsosknm24_kna;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tmtmsoshiki.comsosknm24_kna
     *
     * @param comsosknm24_kna the value for tmtmsoshiki.comsosknm24_kna
     *
     * @mbg.generated Thu Sep 15 17:29:11 JST 2022
     */
    public void setComsosknm24_kna(String comsosknm24_kna) {
        this.comsosknm24_kna = comsosknm24_kna == null ? null : comsosknm24_kna.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tmtmsoshiki.comhyojijun4_num
     *
     * @return the value of tmtmsoshiki.comhyojijun4_num
     *
     * @mbg.generated Thu Sep 15 17:29:11 JST 2022
     */
    public Integer getComhyojijun4_num() {
        return comhyojijun4_num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tmtmsoshiki.comhyojijun4_num
     *
     * @param comhyojijun4_num the value for tmtmsoshiki.comhyojijun4_num
     *
     * @mbg.generated Thu Sep 15 17:29:11 JST 2022
     */
    public void setComhyojijun4_num(Integer comhyojijun4_num) {
        this.comhyojijun4_num = comhyojijun4_num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tmtmsoshiki.comsosk5_cod
     *
     * @return the value of tmtmsoshiki.comsosk5_cod
     *
     * @mbg.generated Thu Sep 15 17:29:11 JST 2022
     */
    public String getComsosk5_cod() {
        return comsosk5_cod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tmtmsoshiki.comsosk5_cod
     *
     * @param comsosk5_cod the value for tmtmsoshiki.comsosk5_cod
     *
     * @mbg.generated Thu Sep 15 17:29:11 JST 2022
     */
    public void setComsosk5_cod(String comsosk5_cod) {
        this.comsosk5_cod = comsosk5_cod == null ? null : comsosk5_cod.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tmtmsoshiki.comsosknm15_knj
     *
     * @return the value of tmtmsoshiki.comsosknm15_knj
     *
     * @mbg.generated Thu Sep 15 17:29:11 JST 2022
     */
    public String getComsosknm15_knj() {
        return comsosknm15_knj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tmtmsoshiki.comsosknm15_knj
     *
     * @param comsosknm15_knj the value for tmtmsoshiki.comsosknm15_knj
     *
     * @mbg.generated Thu Sep 15 17:29:11 JST 2022
     */
    public void setComsosknm15_knj(String comsosknm15_knj) {
        this.comsosknm15_knj = comsosknm15_knj == null ? null : comsosknm15_knj.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tmtmsoshiki.comsosknm25_knj
     *
     * @return the value of tmtmsoshiki.comsosknm25_knj
     *
     * @mbg.generated Thu Sep 15 17:29:11 JST 2022
     */
    public String getComsosknm25_knj() {
        return comsosknm25_knj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tmtmsoshiki.comsosknm25_knj
     *
     * @param comsosknm25_knj the value for tmtmsoshiki.comsosknm25_knj
     *
     * @mbg.generated Thu Sep 15 17:29:11 JST 2022
     */
    public void setComsosknm25_knj(String comsosknm25_knj) {
        this.comsosknm25_knj = comsosknm25_knj == null ? null : comsosknm25_knj.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tmtmsoshiki.comsosknm15_kna
     *
     * @return the value of tmtmsoshiki.comsosknm15_kna
     *
     * @mbg.generated Thu Sep 15 17:29:11 JST 2022
     */
    public String getComsosknm15_kna() {
        return comsosknm15_kna;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tmtmsoshiki.comsosknm15_kna
     *
     * @param comsosknm15_kna the value for tmtmsoshiki.comsosknm15_kna
     *
     * @mbg.generated Thu Sep 15 17:29:11 JST 2022
     */
    public void setComsosknm15_kna(String comsosknm15_kna) {
        this.comsosknm15_kna = comsosknm15_kna == null ? null : comsosknm15_kna.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tmtmsoshiki.comsosknm25_kna
     *
     * @return the value of tmtmsoshiki.comsosknm25_kna
     *
     * @mbg.generated Thu Sep 15 17:29:11 JST 2022
     */
    public String getComsosknm25_kna() {
        return comsosknm25_kna;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tmtmsoshiki.comsosknm25_kna
     *
     * @param comsosknm25_kna the value for tmtmsoshiki.comsosknm25_kna
     *
     * @mbg.generated Thu Sep 15 17:29:11 JST 2022
     */
    public void setComsosknm25_kna(String comsosknm25_kna) {
        this.comsosknm25_kna = comsosknm25_kna == null ? null : comsosknm25_kna.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tmtmsoshiki.comhyojijun5_num
     *
     * @return the value of tmtmsoshiki.comhyojijun5_num
     *
     * @mbg.generated Thu Sep 15 17:29:11 JST 2022
     */
    public Integer getComhyojijun5_num() {
        return comhyojijun5_num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tmtmsoshiki.comhyojijun5_num
     *
     * @param comhyojijun5_num the value for tmtmsoshiki.comhyojijun5_num
     *
     * @mbg.generated Thu Sep 15 17:29:11 JST 2022
     */
    public void setComhyojijun5_num(Integer comhyojijun5_num) {
        this.comhyojijun5_num = comhyojijun5_num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tmtmsoshiki.comsosk6_cod
     *
     * @return the value of tmtmsoshiki.comsosk6_cod
     *
     * @mbg.generated Thu Sep 15 17:29:11 JST 2022
     */
    public String getComsosk6_cod() {
        return comsosk6_cod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tmtmsoshiki.comsosk6_cod
     *
     * @param comsosk6_cod the value for tmtmsoshiki.comsosk6_cod
     *
     * @mbg.generated Thu Sep 15 17:29:11 JST 2022
     */
    public void setComsosk6_cod(String comsosk6_cod) {
        this.comsosk6_cod = comsosk6_cod == null ? null : comsosk6_cod.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tmtmsoshiki.comsosknm16_knj
     *
     * @return the value of tmtmsoshiki.comsosknm16_knj
     *
     * @mbg.generated Thu Sep 15 17:29:11 JST 2022
     */
    public String getComsosknm16_knj() {
        return comsosknm16_knj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tmtmsoshiki.comsosknm16_knj
     *
     * @param comsosknm16_knj the value for tmtmsoshiki.comsosknm16_knj
     *
     * @mbg.generated Thu Sep 15 17:29:11 JST 2022
     */
    public void setComsosknm16_knj(String comsosknm16_knj) {
        this.comsosknm16_knj = comsosknm16_knj == null ? null : comsosknm16_knj.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tmtmsoshiki.comsosknm26_knj
     *
     * @return the value of tmtmsoshiki.comsosknm26_knj
     *
     * @mbg.generated Thu Sep 15 17:29:11 JST 2022
     */
    public String getComsosknm26_knj() {
        return comsosknm26_knj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tmtmsoshiki.comsosknm26_knj
     *
     * @param comsosknm26_knj the value for tmtmsoshiki.comsosknm26_knj
     *
     * @mbg.generated Thu Sep 15 17:29:11 JST 2022
     */
    public void setComsosknm26_knj(String comsosknm26_knj) {
        this.comsosknm26_knj = comsosknm26_knj == null ? null : comsosknm26_knj.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tmtmsoshiki.comsosknm16_kna
     *
     * @return the value of tmtmsoshiki.comsosknm16_kna
     *
     * @mbg.generated Thu Sep 15 17:29:11 JST 2022
     */
    public String getComsosknm16_kna() {
        return comsosknm16_kna;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tmtmsoshiki.comsosknm16_kna
     *
     * @param comsosknm16_kna the value for tmtmsoshiki.comsosknm16_kna
     *
     * @mbg.generated Thu Sep 15 17:29:11 JST 2022
     */
    public void setComsosknm16_kna(String comsosknm16_kna) {
        this.comsosknm16_kna = comsosknm16_kna == null ? null : comsosknm16_kna.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tmtmsoshiki.comsosknm26_kna
     *
     * @return the value of tmtmsoshiki.comsosknm26_kna
     *
     * @mbg.generated Thu Sep 15 17:29:11 JST 2022
     */
    public String getComsosknm26_kna() {
        return comsosknm26_kna;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tmtmsoshiki.comsosknm26_kna
     *
     * @param comsosknm26_kna the value for tmtmsoshiki.comsosknm26_kna
     *
     * @mbg.generated Thu Sep 15 17:29:11 JST 2022
     */
    public void setComsosknm26_kna(String comsosknm26_kna) {
        this.comsosknm26_kna = comsosknm26_kna == null ? null : comsosknm26_kna.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tmtmsoshiki.comhyojijun6_num
     *
     * @return the value of tmtmsoshiki.comhyojijun6_num
     *
     * @mbg.generated Thu Sep 15 17:29:11 JST 2022
     */
    public Integer getComhyojijun6_num() {
        return comhyojijun6_num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tmtmsoshiki.comhyojijun6_num
     *
     * @param comhyojijun6_num the value for tmtmsoshiki.comhyojijun6_num
     *
     * @mbg.generated Thu Sep 15 17:29:11 JST 2022
     */
    public void setComhyojijun6_num(Integer comhyojijun6_num) {
        this.comhyojijun6_num = comhyojijun6_num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tmtmsoshiki.comsosk7_cod
     *
     * @return the value of tmtmsoshiki.comsosk7_cod
     *
     * @mbg.generated Thu Sep 15 17:29:11 JST 2022
     */
    public String getComsosk7_cod() {
        return comsosk7_cod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tmtmsoshiki.comsosk7_cod
     *
     * @param comsosk7_cod the value for tmtmsoshiki.comsosk7_cod
     *
     * @mbg.generated Thu Sep 15 17:29:11 JST 2022
     */
    public void setComsosk7_cod(String comsosk7_cod) {
        this.comsosk7_cod = comsosk7_cod == null ? null : comsosk7_cod.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tmtmsoshiki.comsosknm17_knj
     *
     * @return the value of tmtmsoshiki.comsosknm17_knj
     *
     * @mbg.generated Thu Sep 15 17:29:11 JST 2022
     */
    public String getComsosknm17_knj() {
        return comsosknm17_knj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tmtmsoshiki.comsosknm17_knj
     *
     * @param comsosknm17_knj the value for tmtmsoshiki.comsosknm17_knj
     *
     * @mbg.generated Thu Sep 15 17:29:11 JST 2022
     */
    public void setComsosknm17_knj(String comsosknm17_knj) {
        this.comsosknm17_knj = comsosknm17_knj == null ? null : comsosknm17_knj.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tmtmsoshiki.comsosknm27_knj
     *
     * @return the value of tmtmsoshiki.comsosknm27_knj
     *
     * @mbg.generated Thu Sep 15 17:29:11 JST 2022
     */
    public String getComsosknm27_knj() {
        return comsosknm27_knj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tmtmsoshiki.comsosknm27_knj
     *
     * @param comsosknm27_knj the value for tmtmsoshiki.comsosknm27_knj
     *
     * @mbg.generated Thu Sep 15 17:29:11 JST 2022
     */
    public void setComsosknm27_knj(String comsosknm27_knj) {
        this.comsosknm27_knj = comsosknm27_knj == null ? null : comsosknm27_knj.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tmtmsoshiki.comsosknm17_kna
     *
     * @return the value of tmtmsoshiki.comsosknm17_kna
     *
     * @mbg.generated Thu Sep 15 17:29:11 JST 2022
     */
    public String getComsosknm17_kna() {
        return comsosknm17_kna;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tmtmsoshiki.comsosknm17_kna
     *
     * @param comsosknm17_kna the value for tmtmsoshiki.comsosknm17_kna
     *
     * @mbg.generated Thu Sep 15 17:29:11 JST 2022
     */
    public void setComsosknm17_kna(String comsosknm17_kna) {
        this.comsosknm17_kna = comsosknm17_kna == null ? null : comsosknm17_kna.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tmtmsoshiki.comsosknm27_kna
     *
     * @return the value of tmtmsoshiki.comsosknm27_kna
     *
     * @mbg.generated Thu Sep 15 17:29:11 JST 2022
     */
    public String getComsosknm27_kna() {
        return comsosknm27_kna;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tmtmsoshiki.comsosknm27_kna
     *
     * @param comsosknm27_kna the value for tmtmsoshiki.comsosknm27_kna
     *
     * @mbg.generated Thu Sep 15 17:29:11 JST 2022
     */
    public void setComsosknm27_kna(String comsosknm27_kna) {
        this.comsosknm27_kna = comsosknm27_kna == null ? null : comsosknm27_kna.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tmtmsoshiki.comhyojijun7_num
     *
     * @return the value of tmtmsoshiki.comhyojijun7_num
     *
     * @mbg.generated Thu Sep 15 17:29:11 JST 2022
     */
    public Integer getComhyojijun7_num() {
        return comhyojijun7_num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tmtmsoshiki.comhyojijun7_num
     *
     * @param comhyojijun7_num the value for tmtmsoshiki.comhyojijun7_num
     *
     * @mbg.generated Thu Sep 15 17:29:11 JST 2022
     */
    public void setComhyojijun7_num(Integer comhyojijun7_num) {
        this.comhyojijun7_num = comhyojijun7_num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tmtmsoshiki.comsosk8_cod
     *
     * @return the value of tmtmsoshiki.comsosk8_cod
     *
     * @mbg.generated Thu Sep 15 17:29:11 JST 2022
     */
    public String getComsosk8_cod() {
        return comsosk8_cod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tmtmsoshiki.comsosk8_cod
     *
     * @param comsosk8_cod the value for tmtmsoshiki.comsosk8_cod
     *
     * @mbg.generated Thu Sep 15 17:29:11 JST 2022
     */
    public void setComsosk8_cod(String comsosk8_cod) {
        this.comsosk8_cod = comsosk8_cod == null ? null : comsosk8_cod.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tmtmsoshiki.comsosknm18_knj
     *
     * @return the value of tmtmsoshiki.comsosknm18_knj
     *
     * @mbg.generated Thu Sep 15 17:29:11 JST 2022
     */
    public String getComsosknm18_knj() {
        return comsosknm18_knj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tmtmsoshiki.comsosknm18_knj
     *
     * @param comsosknm18_knj the value for tmtmsoshiki.comsosknm18_knj
     *
     * @mbg.generated Thu Sep 15 17:29:11 JST 2022
     */
    public void setComsosknm18_knj(String comsosknm18_knj) {
        this.comsosknm18_knj = comsosknm18_knj == null ? null : comsosknm18_knj.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tmtmsoshiki.comsosknm28_knj
     *
     * @return the value of tmtmsoshiki.comsosknm28_knj
     *
     * @mbg.generated Thu Sep 15 17:29:11 JST 2022
     */
    public String getComsosknm28_knj() {
        return comsosknm28_knj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tmtmsoshiki.comsosknm28_knj
     *
     * @param comsosknm28_knj the value for tmtmsoshiki.comsosknm28_knj
     *
     * @mbg.generated Thu Sep 15 17:29:11 JST 2022
     */
    public void setComsosknm28_knj(String comsosknm28_knj) {
        this.comsosknm28_knj = comsosknm28_knj == null ? null : comsosknm28_knj.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tmtmsoshiki.comsosknm18_kna
     *
     * @return the value of tmtmsoshiki.comsosknm18_kna
     *
     * @mbg.generated Thu Sep 15 17:29:11 JST 2022
     */
    public String getComsosknm18_kna() {
        return comsosknm18_kna;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tmtmsoshiki.comsosknm18_kna
     *
     * @param comsosknm18_kna the value for tmtmsoshiki.comsosknm18_kna
     *
     * @mbg.generated Thu Sep 15 17:29:11 JST 2022
     */
    public void setComsosknm18_kna(String comsosknm18_kna) {
        this.comsosknm18_kna = comsosknm18_kna == null ? null : comsosknm18_kna.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tmtmsoshiki.comsosknm28_kna
     *
     * @return the value of tmtmsoshiki.comsosknm28_kna
     *
     * @mbg.generated Thu Sep 15 17:29:11 JST 2022
     */
    public String getComsosknm28_kna() {
        return comsosknm28_kna;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tmtmsoshiki.comsosknm28_kna
     *
     * @param comsosknm28_kna the value for tmtmsoshiki.comsosknm28_kna
     *
     * @mbg.generated Thu Sep 15 17:29:11 JST 2022
     */
    public void setComsosknm28_kna(String comsosknm28_kna) {
        this.comsosknm28_kna = comsosknm28_kna == null ? null : comsosknm28_kna.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tmtmsoshiki.comhyojijun8_num
     *
     * @return the value of tmtmsoshiki.comhyojijun8_num
     *
     * @mbg.generated Thu Sep 15 17:29:11 JST 2022
     */
    public Integer getComhyojijun8_num() {
        return comhyojijun8_num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tmtmsoshiki.comhyojijun8_num
     *
     * @param comhyojijun8_num the value for tmtmsoshiki.comhyojijun8_num
     *
     * @mbg.generated Thu Sep 15 17:29:11 JST 2022
     */
    public void setComhyojijun8_num(Integer comhyojijun8_num) {
        this.comhyojijun8_num = comhyojijun8_num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tmtmsoshiki.comsosk9_cod
     *
     * @return the value of tmtmsoshiki.comsosk9_cod
     *
     * @mbg.generated Thu Sep 15 17:29:11 JST 2022
     */
    public String getComsosk9_cod() {
        return comsosk9_cod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tmtmsoshiki.comsosk9_cod
     *
     * @param comsosk9_cod the value for tmtmsoshiki.comsosk9_cod
     *
     * @mbg.generated Thu Sep 15 17:29:11 JST 2022
     */
    public void setComsosk9_cod(String comsosk9_cod) {
        this.comsosk9_cod = comsosk9_cod == null ? null : comsosk9_cod.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tmtmsoshiki.comsosknm19_knj
     *
     * @return the value of tmtmsoshiki.comsosknm19_knj
     *
     * @mbg.generated Thu Sep 15 17:29:11 JST 2022
     */
    public String getComsosknm19_knj() {
        return comsosknm19_knj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tmtmsoshiki.comsosknm19_knj
     *
     * @param comsosknm19_knj the value for tmtmsoshiki.comsosknm19_knj
     *
     * @mbg.generated Thu Sep 15 17:29:11 JST 2022
     */
    public void setComsosknm19_knj(String comsosknm19_knj) {
        this.comsosknm19_knj = comsosknm19_knj == null ? null : comsosknm19_knj.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tmtmsoshiki.comsosknm29_knj
     *
     * @return the value of tmtmsoshiki.comsosknm29_knj
     *
     * @mbg.generated Thu Sep 15 17:29:11 JST 2022
     */
    public String getComsosknm29_knj() {
        return comsosknm29_knj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tmtmsoshiki.comsosknm29_knj
     *
     * @param comsosknm29_knj the value for tmtmsoshiki.comsosknm29_knj
     *
     * @mbg.generated Thu Sep 15 17:29:11 JST 2022
     */
    public void setComsosknm29_knj(String comsosknm29_knj) {
        this.comsosknm29_knj = comsosknm29_knj == null ? null : comsosknm29_knj.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tmtmsoshiki.comsosknm19_kna
     *
     * @return the value of tmtmsoshiki.comsosknm19_kna
     *
     * @mbg.generated Thu Sep 15 17:29:11 JST 2022
     */
    public String getComsosknm19_kna() {
        return comsosknm19_kna;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tmtmsoshiki.comsosknm19_kna
     *
     * @param comsosknm19_kna the value for tmtmsoshiki.comsosknm19_kna
     *
     * @mbg.generated Thu Sep 15 17:29:11 JST 2022
     */
    public void setComsosknm19_kna(String comsosknm19_kna) {
        this.comsosknm19_kna = comsosknm19_kna == null ? null : comsosknm19_kna.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tmtmsoshiki.comsosknm29_kna
     *
     * @return the value of tmtmsoshiki.comsosknm29_kna
     *
     * @mbg.generated Thu Sep 15 17:29:11 JST 2022
     */
    public String getComsosknm29_kna() {
        return comsosknm29_kna;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tmtmsoshiki.comsosknm29_kna
     *
     * @param comsosknm29_kna the value for tmtmsoshiki.comsosknm29_kna
     *
     * @mbg.generated Thu Sep 15 17:29:11 JST 2022
     */
    public void setComsosknm29_kna(String comsosknm29_kna) {
        this.comsosknm29_kna = comsosknm29_kna == null ? null : comsosknm29_kna.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tmtmsoshiki.comhyojijun9_num
     *
     * @return the value of tmtmsoshiki.comhyojijun9_num
     *
     * @mbg.generated Thu Sep 15 17:29:11 JST 2022
     */
    public Integer getComhyojijun9_num() {
        return comhyojijun9_num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tmtmsoshiki.comhyojijun9_num
     *
     * @param comhyojijun9_num the value for tmtmsoshiki.comhyojijun9_num
     *
     * @mbg.generated Thu Sep 15 17:29:11 JST 2022
     */
    public void setComhyojijun9_num(Integer comhyojijun9_num) {
        this.comhyojijun9_num = comhyojijun9_num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tmtmsoshiki.comsosk10_cod
     *
     * @return the value of tmtmsoshiki.comsosk10_cod
     *
     * @mbg.generated Thu Sep 15 17:29:11 JST 2022
     */
    public String getComsosk10_cod() {
        return comsosk10_cod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tmtmsoshiki.comsosk10_cod
     *
     * @param comsosk10_cod the value for tmtmsoshiki.comsosk10_cod
     *
     * @mbg.generated Thu Sep 15 17:29:11 JST 2022
     */
    public void setComsosk10_cod(String comsosk10_cod) {
        this.comsosk10_cod = comsosk10_cod == null ? null : comsosk10_cod.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tmtmsoshiki.comsosknm110_knj
     *
     * @return the value of tmtmsoshiki.comsosknm110_knj
     *
     * @mbg.generated Thu Sep 15 17:29:11 JST 2022
     */
    public String getComsosknm110_knj() {
        return comsosknm110_knj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tmtmsoshiki.comsosknm110_knj
     *
     * @param comsosknm110_knj the value for tmtmsoshiki.comsosknm110_knj
     *
     * @mbg.generated Thu Sep 15 17:29:11 JST 2022
     */
    public void setComsosknm110_knj(String comsosknm110_knj) {
        this.comsosknm110_knj = comsosknm110_knj == null ? null : comsosknm110_knj.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tmtmsoshiki.comsosknm210_knj
     *
     * @return the value of tmtmsoshiki.comsosknm210_knj
     *
     * @mbg.generated Thu Sep 15 17:29:11 JST 2022
     */
    public String getComsosknm210_knj() {
        return comsosknm210_knj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tmtmsoshiki.comsosknm210_knj
     *
     * @param comsosknm210_knj the value for tmtmsoshiki.comsosknm210_knj
     *
     * @mbg.generated Thu Sep 15 17:29:11 JST 2022
     */
    public void setComsosknm210_knj(String comsosknm210_knj) {
        this.comsosknm210_knj = comsosknm210_knj == null ? null : comsosknm210_knj.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tmtmsoshiki.comsosknm110_kna
     *
     * @return the value of tmtmsoshiki.comsosknm110_kna
     *
     * @mbg.generated Thu Sep 15 17:29:11 JST 2022
     */
    public String getComsosknm110_kna() {
        return comsosknm110_kna;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tmtmsoshiki.comsosknm110_kna
     *
     * @param comsosknm110_kna the value for tmtmsoshiki.comsosknm110_kna
     *
     * @mbg.generated Thu Sep 15 17:29:11 JST 2022
     */
    public void setComsosknm110_kna(String comsosknm110_kna) {
        this.comsosknm110_kna = comsosknm110_kna == null ? null : comsosknm110_kna.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tmtmsoshiki.comsosknm210_kna
     *
     * @return the value of tmtmsoshiki.comsosknm210_kna
     *
     * @mbg.generated Thu Sep 15 17:29:11 JST 2022
     */
    public String getComsosknm210_kna() {
        return comsosknm210_kna;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tmtmsoshiki.comsosknm210_kna
     *
     * @param comsosknm210_kna the value for tmtmsoshiki.comsosknm210_kna
     *
     * @mbg.generated Thu Sep 15 17:29:11 JST 2022
     */
    public void setComsosknm210_kna(String comsosknm210_kna) {
        this.comsosknm210_kna = comsosknm210_kna == null ? null : comsosknm210_kna.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tmtmsoshiki.comhyojijun10_num
     *
     * @return the value of tmtmsoshiki.comhyojijun10_num
     *
     * @mbg.generated Thu Sep 15 17:29:11 JST 2022
     */
    public Integer getComhyojijun10_num() {
        return comhyojijun10_num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tmtmsoshiki.comhyojijun10_num
     *
     * @param comhyojijun10_num the value for tmtmsoshiki.comhyojijun10_num
     *
     * @mbg.generated Thu Sep 15 17:29:11 JST 2022
     */
    public void setComhyojijun10_num(Integer comhyojijun10_num) {
        this.comhyojijun10_num = comhyojijun10_num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tmtmsoshiki.comyobi_kbn
     *
     * @return the value of tmtmsoshiki.comyobi_kbn
     *
     * @mbg.generated Thu Sep 15 17:29:11 JST 2022
     */
    public String getComyobi_kbn() {
        return comyobi_kbn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tmtmsoshiki.comyobi_kbn
     *
     * @param comyobi_kbn the value for tmtmsoshiki.comyobi_kbn
     *
     * @mbg.generated Thu Sep 15 17:29:11 JST 2022
     */
    public void setComyobi_kbn(String comyobi_kbn) {
        this.comyobi_kbn = comyobi_kbn == null ? null : comyobi_kbn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tmtmsoshiki.comtekiyoend_ymd
     *
     * @return the value of tmtmsoshiki.comtekiyoend_ymd
     *
     * @mbg.generated Thu Sep 15 17:29:11 JST 2022
     */
    public Date getComtekiyoend_ymd() {
        return comtekiyoend_ymd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tmtmsoshiki.comtekiyoend_ymd
     *
     * @param comtekiyoend_ymd the value for tmtmsoshiki.comtekiyoend_ymd
     *
     * @mbg.generated Thu Sep 15 17:29:11 JST 2022
     */
    public void setComtekiyoend_ymd(Date comtekiyoend_ymd) {
        this.comtekiyoend_ymd = comtekiyoend_ymd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tmtmsoshiki.comcrt_ymd
     *
     * @return the value of tmtmsoshiki.comcrt_ymd
     *
     * @mbg.generated Thu Sep 15 17:29:11 JST 2022
     */
    public Date getComcrt_ymd() {
        return comcrt_ymd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tmtmsoshiki.comcrt_ymd
     *
     * @param comcrt_ymd the value for tmtmsoshiki.comcrt_ymd
     *
     * @mbg.generated Thu Sep 15 17:29:11 JST 2022
     */
    public void setComcrt_ymd(Date comcrt_ymd) {
        this.comcrt_ymd = comcrt_ymd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tmtmsoshiki.comcrtshain_cod
     *
     * @return the value of tmtmsoshiki.comcrtshain_cod
     *
     * @mbg.generated Thu Sep 15 17:29:11 JST 2022
     */
    public String getComcrtshain_cod() {
        return comcrtshain_cod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tmtmsoshiki.comcrtshain_cod
     *
     * @param comcrtshain_cod the value for tmtmsoshiki.comcrtshain_cod
     *
     * @mbg.generated Thu Sep 15 17:29:11 JST 2022
     */
    public void setComcrtshain_cod(String comcrtshain_cod) {
        this.comcrtshain_cod = comcrtshain_cod == null ? null : comcrtshain_cod.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tmtmsoshiki.comupd_ymd
     *
     * @return the value of tmtmsoshiki.comupd_ymd
     *
     * @mbg.generated Thu Sep 15 17:29:11 JST 2022
     */
    public Date getComupd_ymd() {
        return comupd_ymd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tmtmsoshiki.comupd_ymd
     *
     * @param comupd_ymd the value for tmtmsoshiki.comupd_ymd
     *
     * @mbg.generated Thu Sep 15 17:29:11 JST 2022
     */
    public void setComupd_ymd(Date comupd_ymd) {
        this.comupd_ymd = comupd_ymd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tmtmsoshiki.comupdshain_cod
     *
     * @return the value of tmtmsoshiki.comupdshain_cod
     *
     * @mbg.generated Thu Sep 15 17:29:11 JST 2022
     */
    public String getComupdshain_cod() {
        return comupdshain_cod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tmtmsoshiki.comupdshain_cod
     *
     * @param comupdshain_cod the value for tmtmsoshiki.comupdshain_cod
     *
     * @mbg.generated Thu Sep 15 17:29:11 JST 2022
     */
    public void setComupdshain_cod(String comupdshain_cod) {
        this.comupdshain_cod = comupdshain_cod == null ? null : comupdshain_cod.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tmtmsoshiki
     *
     * @mbg.generated Thu Sep 15 17:29:11 JST 2022
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Tmtmsoshiki other = (Tmtmsoshiki) that;
        return (this.getComgyomu_kbn() == null ? other.getComgyomu_kbn() == null : this.getComgyomu_kbn().equals(other.getComgyomu_kbn()))
            && (this.getComten_cod() == null ? other.getComten_cod() == null : this.getComten_cod().equals(other.getComten_cod()))
            && (this.getComtekiyostr_ymd() == null ? other.getComtekiyostr_ymd() == null : this.getComtekiyostr_ymd().equals(other.getComtekiyostr_ymd()))
            && (this.getComsosk1_cod() == null ? other.getComsosk1_cod() == null : this.getComsosk1_cod().equals(other.getComsosk1_cod()))
            && (this.getComsosknm11_knj() == null ? other.getComsosknm11_knj() == null : this.getComsosknm11_knj().equals(other.getComsosknm11_knj()))
            && (this.getComsosknm21_knj() == null ? other.getComsosknm21_knj() == null : this.getComsosknm21_knj().equals(other.getComsosknm21_knj()))
            && (this.getComsosknm11_kna() == null ? other.getComsosknm11_kna() == null : this.getComsosknm11_kna().equals(other.getComsosknm11_kna()))
            && (this.getComsosknm21_kna() == null ? other.getComsosknm21_kna() == null : this.getComsosknm21_kna().equals(other.getComsosknm21_kna()))
            && (this.getComhyojijun1_num() == null ? other.getComhyojijun1_num() == null : this.getComhyojijun1_num().equals(other.getComhyojijun1_num()))
            && (this.getComsosk2_cod() == null ? other.getComsosk2_cod() == null : this.getComsosk2_cod().equals(other.getComsosk2_cod()))
            && (this.getComsosknm12_knj() == null ? other.getComsosknm12_knj() == null : this.getComsosknm12_knj().equals(other.getComsosknm12_knj()))
            && (this.getComsosknm22_knj() == null ? other.getComsosknm22_knj() == null : this.getComsosknm22_knj().equals(other.getComsosknm22_knj()))
            && (this.getComsosknm12_kna() == null ? other.getComsosknm12_kna() == null : this.getComsosknm12_kna().equals(other.getComsosknm12_kna()))
            && (this.getComsosknm22_kna() == null ? other.getComsosknm22_kna() == null : this.getComsosknm22_kna().equals(other.getComsosknm22_kna()))
            && (this.getComhyojijun2_num() == null ? other.getComhyojijun2_num() == null : this.getComhyojijun2_num().equals(other.getComhyojijun2_num()))
            && (this.getComsosk3_cod() == null ? other.getComsosk3_cod() == null : this.getComsosk3_cod().equals(other.getComsosk3_cod()))
            && (this.getComsosknm13_knj() == null ? other.getComsosknm13_knj() == null : this.getComsosknm13_knj().equals(other.getComsosknm13_knj()))
            && (this.getComsosknm23_knj() == null ? other.getComsosknm23_knj() == null : this.getComsosknm23_knj().equals(other.getComsosknm23_knj()))
            && (this.getComsosknm13_kna() == null ? other.getComsosknm13_kna() == null : this.getComsosknm13_kna().equals(other.getComsosknm13_kna()))
            && (this.getComsosknm23_kna() == null ? other.getComsosknm23_kna() == null : this.getComsosknm23_kna().equals(other.getComsosknm23_kna()))
            && (this.getComhyojijun3_num() == null ? other.getComhyojijun3_num() == null : this.getComhyojijun3_num().equals(other.getComhyojijun3_num()))
            && (this.getComsosk4_cod() == null ? other.getComsosk4_cod() == null : this.getComsosk4_cod().equals(other.getComsosk4_cod()))
            && (this.getComsosknm14_knj() == null ? other.getComsosknm14_knj() == null : this.getComsosknm14_knj().equals(other.getComsosknm14_knj()))
            && (this.getComsosknm24_knj() == null ? other.getComsosknm24_knj() == null : this.getComsosknm24_knj().equals(other.getComsosknm24_knj()))
            && (this.getComsosknm14_kna() == null ? other.getComsosknm14_kna() == null : this.getComsosknm14_kna().equals(other.getComsosknm14_kna()))
            && (this.getComsosknm24_kna() == null ? other.getComsosknm24_kna() == null : this.getComsosknm24_kna().equals(other.getComsosknm24_kna()))
            && (this.getComhyojijun4_num() == null ? other.getComhyojijun4_num() == null : this.getComhyojijun4_num().equals(other.getComhyojijun4_num()))
            && (this.getComsosk5_cod() == null ? other.getComsosk5_cod() == null : this.getComsosk5_cod().equals(other.getComsosk5_cod()))
            && (this.getComsosknm15_knj() == null ? other.getComsosknm15_knj() == null : this.getComsosknm15_knj().equals(other.getComsosknm15_knj()))
            && (this.getComsosknm25_knj() == null ? other.getComsosknm25_knj() == null : this.getComsosknm25_knj().equals(other.getComsosknm25_knj()))
            && (this.getComsosknm15_kna() == null ? other.getComsosknm15_kna() == null : this.getComsosknm15_kna().equals(other.getComsosknm15_kna()))
            && (this.getComsosknm25_kna() == null ? other.getComsosknm25_kna() == null : this.getComsosknm25_kna().equals(other.getComsosknm25_kna()))
            && (this.getComhyojijun5_num() == null ? other.getComhyojijun5_num() == null : this.getComhyojijun5_num().equals(other.getComhyojijun5_num()))
            && (this.getComsosk6_cod() == null ? other.getComsosk6_cod() == null : this.getComsosk6_cod().equals(other.getComsosk6_cod()))
            && (this.getComsosknm16_knj() == null ? other.getComsosknm16_knj() == null : this.getComsosknm16_knj().equals(other.getComsosknm16_knj()))
            && (this.getComsosknm26_knj() == null ? other.getComsosknm26_knj() == null : this.getComsosknm26_knj().equals(other.getComsosknm26_knj()))
            && (this.getComsosknm16_kna() == null ? other.getComsosknm16_kna() == null : this.getComsosknm16_kna().equals(other.getComsosknm16_kna()))
            && (this.getComsosknm26_kna() == null ? other.getComsosknm26_kna() == null : this.getComsosknm26_kna().equals(other.getComsosknm26_kna()))
            && (this.getComhyojijun6_num() == null ? other.getComhyojijun6_num() == null : this.getComhyojijun6_num().equals(other.getComhyojijun6_num()))
            && (this.getComsosk7_cod() == null ? other.getComsosk7_cod() == null : this.getComsosk7_cod().equals(other.getComsosk7_cod()))
            && (this.getComsosknm17_knj() == null ? other.getComsosknm17_knj() == null : this.getComsosknm17_knj().equals(other.getComsosknm17_knj()))
            && (this.getComsosknm27_knj() == null ? other.getComsosknm27_knj() == null : this.getComsosknm27_knj().equals(other.getComsosknm27_knj()))
            && (this.getComsosknm17_kna() == null ? other.getComsosknm17_kna() == null : this.getComsosknm17_kna().equals(other.getComsosknm17_kna()))
            && (this.getComsosknm27_kna() == null ? other.getComsosknm27_kna() == null : this.getComsosknm27_kna().equals(other.getComsosknm27_kna()))
            && (this.getComhyojijun7_num() == null ? other.getComhyojijun7_num() == null : this.getComhyojijun7_num().equals(other.getComhyojijun7_num()))
            && (this.getComsosk8_cod() == null ? other.getComsosk8_cod() == null : this.getComsosk8_cod().equals(other.getComsosk8_cod()))
            && (this.getComsosknm18_knj() == null ? other.getComsosknm18_knj() == null : this.getComsosknm18_knj().equals(other.getComsosknm18_knj()))
            && (this.getComsosknm28_knj() == null ? other.getComsosknm28_knj() == null : this.getComsosknm28_knj().equals(other.getComsosknm28_knj()))
            && (this.getComsosknm18_kna() == null ? other.getComsosknm18_kna() == null : this.getComsosknm18_kna().equals(other.getComsosknm18_kna()))
            && (this.getComsosknm28_kna() == null ? other.getComsosknm28_kna() == null : this.getComsosknm28_kna().equals(other.getComsosknm28_kna()))
            && (this.getComhyojijun8_num() == null ? other.getComhyojijun8_num() == null : this.getComhyojijun8_num().equals(other.getComhyojijun8_num()))
            && (this.getComsosk9_cod() == null ? other.getComsosk9_cod() == null : this.getComsosk9_cod().equals(other.getComsosk9_cod()))
            && (this.getComsosknm19_knj() == null ? other.getComsosknm19_knj() == null : this.getComsosknm19_knj().equals(other.getComsosknm19_knj()))
            && (this.getComsosknm29_knj() == null ? other.getComsosknm29_knj() == null : this.getComsosknm29_knj().equals(other.getComsosknm29_knj()))
            && (this.getComsosknm19_kna() == null ? other.getComsosknm19_kna() == null : this.getComsosknm19_kna().equals(other.getComsosknm19_kna()))
            && (this.getComsosknm29_kna() == null ? other.getComsosknm29_kna() == null : this.getComsosknm29_kna().equals(other.getComsosknm29_kna()))
            && (this.getComhyojijun9_num() == null ? other.getComhyojijun9_num() == null : this.getComhyojijun9_num().equals(other.getComhyojijun9_num()))
            && (this.getComsosk10_cod() == null ? other.getComsosk10_cod() == null : this.getComsosk10_cod().equals(other.getComsosk10_cod()))
            && (this.getComsosknm110_knj() == null ? other.getComsosknm110_knj() == null : this.getComsosknm110_knj().equals(other.getComsosknm110_knj()))
            && (this.getComsosknm210_knj() == null ? other.getComsosknm210_knj() == null : this.getComsosknm210_knj().equals(other.getComsosknm210_knj()))
            && (this.getComsosknm110_kna() == null ? other.getComsosknm110_kna() == null : this.getComsosknm110_kna().equals(other.getComsosknm110_kna()))
            && (this.getComsosknm210_kna() == null ? other.getComsosknm210_kna() == null : this.getComsosknm210_kna().equals(other.getComsosknm210_kna()))
            && (this.getComhyojijun10_num() == null ? other.getComhyojijun10_num() == null : this.getComhyojijun10_num().equals(other.getComhyojijun10_num()))
            && (this.getComyobi_kbn() == null ? other.getComyobi_kbn() == null : this.getComyobi_kbn().equals(other.getComyobi_kbn()))
            && (this.getComtekiyoend_ymd() == null ? other.getComtekiyoend_ymd() == null : this.getComtekiyoend_ymd().equals(other.getComtekiyoend_ymd()))
            && (this.getComcrt_ymd() == null ? other.getComcrt_ymd() == null : this.getComcrt_ymd().equals(other.getComcrt_ymd()))
            && (this.getComcrtshain_cod() == null ? other.getComcrtshain_cod() == null : this.getComcrtshain_cod().equals(other.getComcrtshain_cod()))
            && (this.getComupd_ymd() == null ? other.getComupd_ymd() == null : this.getComupd_ymd().equals(other.getComupd_ymd()))
            && (this.getComupdshain_cod() == null ? other.getComupdshain_cod() == null : this.getComupdshain_cod().equals(other.getComupdshain_cod()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tmtmsoshiki
     *
     * @mbg.generated Thu Sep 15 17:29:11 JST 2022
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getComgyomu_kbn() == null) ? 0 : getComgyomu_kbn().hashCode());
        result = prime * result + ((getComten_cod() == null) ? 0 : getComten_cod().hashCode());
        result = prime * result + ((getComtekiyostr_ymd() == null) ? 0 : getComtekiyostr_ymd().hashCode());
        result = prime * result + ((getComsosk1_cod() == null) ? 0 : getComsosk1_cod().hashCode());
        result = prime * result + ((getComsosknm11_knj() == null) ? 0 : getComsosknm11_knj().hashCode());
        result = prime * result + ((getComsosknm21_knj() == null) ? 0 : getComsosknm21_knj().hashCode());
        result = prime * result + ((getComsosknm11_kna() == null) ? 0 : getComsosknm11_kna().hashCode());
        result = prime * result + ((getComsosknm21_kna() == null) ? 0 : getComsosknm21_kna().hashCode());
        result = prime * result + ((getComhyojijun1_num() == null) ? 0 : getComhyojijun1_num().hashCode());
        result = prime * result + ((getComsosk2_cod() == null) ? 0 : getComsosk2_cod().hashCode());
        result = prime * result + ((getComsosknm12_knj() == null) ? 0 : getComsosknm12_knj().hashCode());
        result = prime * result + ((getComsosknm22_knj() == null) ? 0 : getComsosknm22_knj().hashCode());
        result = prime * result + ((getComsosknm12_kna() == null) ? 0 : getComsosknm12_kna().hashCode());
        result = prime * result + ((getComsosknm22_kna() == null) ? 0 : getComsosknm22_kna().hashCode());
        result = prime * result + ((getComhyojijun2_num() == null) ? 0 : getComhyojijun2_num().hashCode());
        result = prime * result + ((getComsosk3_cod() == null) ? 0 : getComsosk3_cod().hashCode());
        result = prime * result + ((getComsosknm13_knj() == null) ? 0 : getComsosknm13_knj().hashCode());
        result = prime * result + ((getComsosknm23_knj() == null) ? 0 : getComsosknm23_knj().hashCode());
        result = prime * result + ((getComsosknm13_kna() == null) ? 0 : getComsosknm13_kna().hashCode());
        result = prime * result + ((getComsosknm23_kna() == null) ? 0 : getComsosknm23_kna().hashCode());
        result = prime * result + ((getComhyojijun3_num() == null) ? 0 : getComhyojijun3_num().hashCode());
        result = prime * result + ((getComsosk4_cod() == null) ? 0 : getComsosk4_cod().hashCode());
        result = prime * result + ((getComsosknm14_knj() == null) ? 0 : getComsosknm14_knj().hashCode());
        result = prime * result + ((getComsosknm24_knj() == null) ? 0 : getComsosknm24_knj().hashCode());
        result = prime * result + ((getComsosknm14_kna() == null) ? 0 : getComsosknm14_kna().hashCode());
        result = prime * result + ((getComsosknm24_kna() == null) ? 0 : getComsosknm24_kna().hashCode());
        result = prime * result + ((getComhyojijun4_num() == null) ? 0 : getComhyojijun4_num().hashCode());
        result = prime * result + ((getComsosk5_cod() == null) ? 0 : getComsosk5_cod().hashCode());
        result = prime * result + ((getComsosknm15_knj() == null) ? 0 : getComsosknm15_knj().hashCode());
        result = prime * result + ((getComsosknm25_knj() == null) ? 0 : getComsosknm25_knj().hashCode());
        result = prime * result + ((getComsosknm15_kna() == null) ? 0 : getComsosknm15_kna().hashCode());
        result = prime * result + ((getComsosknm25_kna() == null) ? 0 : getComsosknm25_kna().hashCode());
        result = prime * result + ((getComhyojijun5_num() == null) ? 0 : getComhyojijun5_num().hashCode());
        result = prime * result + ((getComsosk6_cod() == null) ? 0 : getComsosk6_cod().hashCode());
        result = prime * result + ((getComsosknm16_knj() == null) ? 0 : getComsosknm16_knj().hashCode());
        result = prime * result + ((getComsosknm26_knj() == null) ? 0 : getComsosknm26_knj().hashCode());
        result = prime * result + ((getComsosknm16_kna() == null) ? 0 : getComsosknm16_kna().hashCode());
        result = prime * result + ((getComsosknm26_kna() == null) ? 0 : getComsosknm26_kna().hashCode());
        result = prime * result + ((getComhyojijun6_num() == null) ? 0 : getComhyojijun6_num().hashCode());
        result = prime * result + ((getComsosk7_cod() == null) ? 0 : getComsosk7_cod().hashCode());
        result = prime * result + ((getComsosknm17_knj() == null) ? 0 : getComsosknm17_knj().hashCode());
        result = prime * result + ((getComsosknm27_knj() == null) ? 0 : getComsosknm27_knj().hashCode());
        result = prime * result + ((getComsosknm17_kna() == null) ? 0 : getComsosknm17_kna().hashCode());
        result = prime * result + ((getComsosknm27_kna() == null) ? 0 : getComsosknm27_kna().hashCode());
        result = prime * result + ((getComhyojijun7_num() == null) ? 0 : getComhyojijun7_num().hashCode());
        result = prime * result + ((getComsosk8_cod() == null) ? 0 : getComsosk8_cod().hashCode());
        result = prime * result + ((getComsosknm18_knj() == null) ? 0 : getComsosknm18_knj().hashCode());
        result = prime * result + ((getComsosknm28_knj() == null) ? 0 : getComsosknm28_knj().hashCode());
        result = prime * result + ((getComsosknm18_kna() == null) ? 0 : getComsosknm18_kna().hashCode());
        result = prime * result + ((getComsosknm28_kna() == null) ? 0 : getComsosknm28_kna().hashCode());
        result = prime * result + ((getComhyojijun8_num() == null) ? 0 : getComhyojijun8_num().hashCode());
        result = prime * result + ((getComsosk9_cod() == null) ? 0 : getComsosk9_cod().hashCode());
        result = prime * result + ((getComsosknm19_knj() == null) ? 0 : getComsosknm19_knj().hashCode());
        result = prime * result + ((getComsosknm29_knj() == null) ? 0 : getComsosknm29_knj().hashCode());
        result = prime * result + ((getComsosknm19_kna() == null) ? 0 : getComsosknm19_kna().hashCode());
        result = prime * result + ((getComsosknm29_kna() == null) ? 0 : getComsosknm29_kna().hashCode());
        result = prime * result + ((getComhyojijun9_num() == null) ? 0 : getComhyojijun9_num().hashCode());
        result = prime * result + ((getComsosk10_cod() == null) ? 0 : getComsosk10_cod().hashCode());
        result = prime * result + ((getComsosknm110_knj() == null) ? 0 : getComsosknm110_knj().hashCode());
        result = prime * result + ((getComsosknm210_knj() == null) ? 0 : getComsosknm210_knj().hashCode());
        result = prime * result + ((getComsosknm110_kna() == null) ? 0 : getComsosknm110_kna().hashCode());
        result = prime * result + ((getComsosknm210_kna() == null) ? 0 : getComsosknm210_kna().hashCode());
        result = prime * result + ((getComhyojijun10_num() == null) ? 0 : getComhyojijun10_num().hashCode());
        result = prime * result + ((getComyobi_kbn() == null) ? 0 : getComyobi_kbn().hashCode());
        result = prime * result + ((getComtekiyoend_ymd() == null) ? 0 : getComtekiyoend_ymd().hashCode());
        result = prime * result + ((getComcrt_ymd() == null) ? 0 : getComcrt_ymd().hashCode());
        result = prime * result + ((getComcrtshain_cod() == null) ? 0 : getComcrtshain_cod().hashCode());
        result = prime * result + ((getComupd_ymd() == null) ? 0 : getComupd_ymd().hashCode());
        result = prime * result + ((getComupdshain_cod() == null) ? 0 : getComupdshain_cod().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tmtmsoshiki
     *
     * @mbg.generated Thu Sep 15 17:29:11 JST 2022
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", comsosk1_cod=").append(comsosk1_cod);
        sb.append(", comsosknm11_knj=").append(comsosknm11_knj);
        sb.append(", comsosknm21_knj=").append(comsosknm21_knj);
        sb.append(", comsosknm11_kna=").append(comsosknm11_kna);
        sb.append(", comsosknm21_kna=").append(comsosknm21_kna);
        sb.append(", comhyojijun1_num=").append(comhyojijun1_num);
        sb.append(", comsosk2_cod=").append(comsosk2_cod);
        sb.append(", comsosknm12_knj=").append(comsosknm12_knj);
        sb.append(", comsosknm22_knj=").append(comsosknm22_knj);
        sb.append(", comsosknm12_kna=").append(comsosknm12_kna);
        sb.append(", comsosknm22_kna=").append(comsosknm22_kna);
        sb.append(", comhyojijun2_num=").append(comhyojijun2_num);
        sb.append(", comsosk3_cod=").append(comsosk3_cod);
        sb.append(", comsosknm13_knj=").append(comsosknm13_knj);
        sb.append(", comsosknm23_knj=").append(comsosknm23_knj);
        sb.append(", comsosknm13_kna=").append(comsosknm13_kna);
        sb.append(", comsosknm23_kna=").append(comsosknm23_kna);
        sb.append(", comhyojijun3_num=").append(comhyojijun3_num);
        sb.append(", comsosk4_cod=").append(comsosk4_cod);
        sb.append(", comsosknm14_knj=").append(comsosknm14_knj);
        sb.append(", comsosknm24_knj=").append(comsosknm24_knj);
        sb.append(", comsosknm14_kna=").append(comsosknm14_kna);
        sb.append(", comsosknm24_kna=").append(comsosknm24_kna);
        sb.append(", comhyojijun4_num=").append(comhyojijun4_num);
        sb.append(", comsosk5_cod=").append(comsosk5_cod);
        sb.append(", comsosknm15_knj=").append(comsosknm15_knj);
        sb.append(", comsosknm25_knj=").append(comsosknm25_knj);
        sb.append(", comsosknm15_kna=").append(comsosknm15_kna);
        sb.append(", comsosknm25_kna=").append(comsosknm25_kna);
        sb.append(", comhyojijun5_num=").append(comhyojijun5_num);
        sb.append(", comsosk6_cod=").append(comsosk6_cod);
        sb.append(", comsosknm16_knj=").append(comsosknm16_knj);
        sb.append(", comsosknm26_knj=").append(comsosknm26_knj);
        sb.append(", comsosknm16_kna=").append(comsosknm16_kna);
        sb.append(", comsosknm26_kna=").append(comsosknm26_kna);
        sb.append(", comhyojijun6_num=").append(comhyojijun6_num);
        sb.append(", comsosk7_cod=").append(comsosk7_cod);
        sb.append(", comsosknm17_knj=").append(comsosknm17_knj);
        sb.append(", comsosknm27_knj=").append(comsosknm27_knj);
        sb.append(", comsosknm17_kna=").append(comsosknm17_kna);
        sb.append(", comsosknm27_kna=").append(comsosknm27_kna);
        sb.append(", comhyojijun7_num=").append(comhyojijun7_num);
        sb.append(", comsosk8_cod=").append(comsosk8_cod);
        sb.append(", comsosknm18_knj=").append(comsosknm18_knj);
        sb.append(", comsosknm28_knj=").append(comsosknm28_knj);
        sb.append(", comsosknm18_kna=").append(comsosknm18_kna);
        sb.append(", comsosknm28_kna=").append(comsosknm28_kna);
        sb.append(", comhyojijun8_num=").append(comhyojijun8_num);
        sb.append(", comsosk9_cod=").append(comsosk9_cod);
        sb.append(", comsosknm19_knj=").append(comsosknm19_knj);
        sb.append(", comsosknm29_knj=").append(comsosknm29_knj);
        sb.append(", comsosknm19_kna=").append(comsosknm19_kna);
        sb.append(", comsosknm29_kna=").append(comsosknm29_kna);
        sb.append(", comhyojijun9_num=").append(comhyojijun9_num);
        sb.append(", comsosk10_cod=").append(comsosk10_cod);
        sb.append(", comsosknm110_knj=").append(comsosknm110_knj);
        sb.append(", comsosknm210_knj=").append(comsosknm210_knj);
        sb.append(", comsosknm110_kna=").append(comsosknm110_kna);
        sb.append(", comsosknm210_kna=").append(comsosknm210_kna);
        sb.append(", comhyojijun10_num=").append(comhyojijun10_num);
        sb.append(", comyobi_kbn=").append(comyobi_kbn);
        sb.append(", comtekiyoend_ymd=").append(comtekiyoend_ymd);
        sb.append(", comcrt_ymd=").append(comcrt_ymd);
        sb.append(", comcrtshain_cod=").append(comcrtshain_cod);
        sb.append(", comupd_ymd=").append(comupd_ymd);
        sb.append(", comupdshain_cod=").append(comupdshain_cod);
        sb.append("]");
        return sb.toString();
    }
}