package com.wetech.ryutsumodel.model.entity;

import java.util.Date;

public class TmtmsoshikiKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tmtmsoshiki.comgyomu_kbn
     *
     * @mbg.generated Thu Sep 15 17:29:11 JST 2022
     */
    private Short comgyomu_kbn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tmtmsoshiki.comten_cod
     *
     * @mbg.generated Thu Sep 15 17:29:11 JST 2022
     */
    private String comten_cod;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tmtmsoshiki.comtekiyostr_ymd
     *
     * @mbg.generated Thu Sep 15 17:29:11 JST 2022
     */
    private Date comtekiyostr_ymd;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tmtmsoshiki.comgyomu_kbn
     *
     * @return the value of tmtmsoshiki.comgyomu_kbn
     *
     * @mbg.generated Thu Sep 15 17:29:11 JST 2022
     */
    public Short getComgyomu_kbn() {
        return comgyomu_kbn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tmtmsoshiki.comgyomu_kbn
     *
     * @param comgyomu_kbn the value for tmtmsoshiki.comgyomu_kbn
     *
     * @mbg.generated Thu Sep 15 17:29:11 JST 2022
     */
    public void setComgyomu_kbn(Short comgyomu_kbn) {
        this.comgyomu_kbn = comgyomu_kbn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tmtmsoshiki.comten_cod
     *
     * @return the value of tmtmsoshiki.comten_cod
     *
     * @mbg.generated Thu Sep 15 17:29:11 JST 2022
     */
    public String getComten_cod() {
        return comten_cod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tmtmsoshiki.comten_cod
     *
     * @param comten_cod the value for tmtmsoshiki.comten_cod
     *
     * @mbg.generated Thu Sep 15 17:29:11 JST 2022
     */
    public void setComten_cod(String comten_cod) {
        this.comten_cod = comten_cod == null ? null : comten_cod.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tmtmsoshiki.comtekiyostr_ymd
     *
     * @return the value of tmtmsoshiki.comtekiyostr_ymd
     *
     * @mbg.generated Thu Sep 15 17:29:11 JST 2022
     */
    public Date getComtekiyostr_ymd() {
        return comtekiyostr_ymd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tmtmsoshiki.comtekiyostr_ymd
     *
     * @param comtekiyostr_ymd the value for tmtmsoshiki.comtekiyostr_ymd
     *
     * @mbg.generated Thu Sep 15 17:29:11 JST 2022
     */
    public void setComtekiyostr_ymd(Date comtekiyostr_ymd) {
        this.comtekiyostr_ymd = comtekiyostr_ymd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tmtmsoshiki
     *
     * @mbg.generated Thu Sep 15 17:29:11 JST 2022
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        TmtmsoshikiKey other = (TmtmsoshikiKey) that;
        return (this.getComgyomu_kbn() == null ? other.getComgyomu_kbn() == null : this.getComgyomu_kbn().equals(other.getComgyomu_kbn()))
            && (this.getComten_cod() == null ? other.getComten_cod() == null : this.getComten_cod().equals(other.getComten_cod()))
            && (this.getComtekiyostr_ymd() == null ? other.getComtekiyostr_ymd() == null : this.getComtekiyostr_ymd().equals(other.getComtekiyostr_ymd()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tmtmsoshiki
     *
     * @mbg.generated Thu Sep 15 17:29:11 JST 2022
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getComgyomu_kbn() == null) ? 0 : getComgyomu_kbn().hashCode());
        result = prime * result + ((getComten_cod() == null) ? 0 : getComten_cod().hashCode());
        result = prime * result + ((getComtekiyostr_ymd() == null) ? 0 : getComtekiyostr_ymd().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tmtmsoshiki
     *
     * @mbg.generated Thu Sep 15 17:29:11 JST 2022
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", comgyomu_kbn=").append(comgyomu_kbn);
        sb.append(", comten_cod=").append(comten_cod);
        sb.append(", comtekiyostr_ymd=").append(comtekiyostr_ymd);
        sb.append("]");
        return sb.toString();
    }
}